### ISSUE TITLE
Study efficacy of other guides and boxes

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#1]
1) Review the content of the boxes
2) Do user interviews on users of said boxes
- [ ] Coding Related
  - [ ] **Girls who Code**
    - [ ] [Details](https://github.com/jonleung/hackedu-private/issues/2)

- [ ] Other Reproducible Models
  - [ ] **CodeNow**
    - [ ] Read contents
    - [ ] Talk to at least 10 years
  - [ ] **CoderDojo**
    - [ ] Read contents
    - [ ] Talk to at least 10 years
  - [ ] **Teals**
    - [ ] Read contents
    - [ ] Talk to at least 10 years
  - [ ] **Google CS FIRST**
    - [ ] Read contents
    - [ ] Talk to at least 10 years
  - [ ] **CodeClub**
    - [ ] Read contents
    - [ ] Talk to at least 10 years

**Comment by zachlatta** [comment]
Is there a deliverable for this task? Perhaps putting together some doc
that's an overview of the different offerings or something.

**Comment by zachlatta** [comment]
One of the things you can do is link to other tasks simply by saying jonleung/hackedu-private#2.

**Comment by MaxWofford** [comment]
@jonleung Let's close this issue if there isn't a well-defined deliverable.
