### ISSUE TITLE
Week 1 Club Lessons!

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#10]
This week I made a Twilio calling challenge in python that focuses on learning how to Google to say something out loud to deactivate a bomb. Will keep you guys posted on how it goes!

https://github.com/jonleung/Twilio-Calling-Challenge-part-2-of-twilio-sms-challenege-/blob/master/README.md

**Comment by zachlatta** [comment]
Awesome! :shipit:

Perhaps put it in a PR?

**Comment by MaxWofford** [comment]
@jonleung Is there an actionable goal that you plan on finishing to this issue?

**Comment by zachlatta** [comment]
Closing for now due to lack of response.
