### ISSUE TITLE
Write Labs Rejection Email

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#107]
Let them know that even though they won't be part of the Labs program, we would like to invite them to be a hackEDU club (what does that mean?).

Include call-to-action to join the Facebook Leaders Group: https://www.facebook.com/groups/1501083703514499/

We want them all to introduce themselves but that will get boring after awhile. What structure can we provide for their intro post that would end up also spurring discussion and being interesting? Maybe we can have them ask for help with whatever they think will be their biggest challenge with their club this year.

I feel comfortable sending this email -- I interviewed the teams, but I need some help figuring out what to say re: being a hackEDU club since that's currently poorly defined and won't be well-defined for a while. Would love to pair with you on this, @jonleung.

**Comment by jonleung** [comment]
@hellyeah sounds good! Just ping me in IRC when you want to discuss. Note that I have a big deadline to meet at the end of the day today so I may not be able to commit that much time.

**Comment by hellyeah** [comment]
Totally cool. I think the main thing for me is that this is blocking on figuring out the guidelines for introducing yourself in the Leaders FB Group. See #117

**Comment by hellyeah** [comment]
https://gist.github.com/hellyeah/d397f84d0e42e6472982

**Comment by hellyeah** [comment]
Sending PR
