### ISSUE TITLE
Add all club leaders to hackEDU Leaders Facebook Group

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#108]

**Comment by jonleung** [comment]
We'll need to create a guideline on how new hackers introduce themselves on the group first. @hellyeah will create an issue for this.

**Comment by hellyeah** [comment]
[ ] add 10 leaders and have them make intros

**Comment by zachlatta** [comment]
Any updates on this?

On Thu, Sep 10, 2015 at 7:44 AM, David Fontenot <notifications@github.com>
wrote:

> [ ] add 10 leaders and have them make intros
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/108#issuecomment-139268204>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
Blocking on #264

**Comment by hellyeah** [comment]
Shifting focus to Slack. We should revisit the Facebook Group in the future.
