### ISSUE TITLE
Create new public Facebook Group for all hackEDU leaders and those clubs' members

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#109]
Leaders should be heavily encouraged to add their members to this group once we get it going. Will be cool for them to be part of a broader community.

Think HS Hackers but we emphasize core values, specifically inclusion and mentorship, from the start. 

We should adopt a Code of Conduct before we launch this group. Here's the one we're developing openly for HH: http://hh.gd/conduct

**Comment by jonleung** [comment]
Dependent on #117, which tracks the code of conduct.

**Comment by zachlatta** [comment]
Created https://www.facebook.com/groups/1647912265454317/ and added @jonleung, @MaxWofford, and @hellyeah as admins.

Still need to adopt a code of conduct. @hellyeah can you take point on that?

**Comment by hellyeah** [comment]
Blocking on hackedu/meta#117

**Comment by zachlatta** [comment]
Moved to the ideas column because we've decided to prioritize getting the main leaders Facebook group going before starting this group as well.

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#302
