### ISSUE TITLE
Encourage club leaders to add their club members to the public Facebook Group

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#110]
We should give them copy that emphasizes our values from before their members even enter the Facebook Group.

This blocks on #109

**Comment by zachlatta** [comment]
@jonleung perhaps this may be a good opportunity to start clarifying our
organizational values as well?

On Thu, Aug 27, 2015 at 3:15 PM, David Fontenot <notifications@github.com>
wrote:

> We should give them copy that emphasizes our values from before their
> members even enter the Facebook Group.
>
> This is
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/110>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta, I agree. Any specific actionable steps that you think we can take on this @zachlatta?

**Comment by zachlatta** [comment]
Should we still plan on doing this?

**Comment by paked** [comment]
Do we even have a public facebook group?

**Comment by jonleung** [comment]
@paked we want to create one.

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#298
