### ISSUE TITLE
Schedule initial call with Labs cohort 1

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#112]

**Comment by zachlatta** [comment]
I created a Doodle link to poll everyone for times and sent it to the Messenger group. Waiting on all of their responses.

**Comment by zachlatta** [comment]
Alright, so everyone has responded and it's now pretty late. Going to confirm 2PM on Sunday with everyone in the morning.

**Comment by zachlatta** [comment]
Alright, there's a bit of a snag. 2PM on Sunday doesn't work for two of the leaders.

Trying to figure out a new time.

**Comment by hellyeah** [comment]
How did this go?

**Comment by zachlatta** [comment]
It happened! It went alright.
