### ISSUE TITLE
Start Messenger Group Chat with Labs Cohort 2

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#113]

**Comment by hellyeah** [comment]
Amy is out of the country for another few days. Would anyone be opposed to starting the Group Chat for Cohort 2 next week when she gets back? 

That would make the call referenced in #114 happen next weekend probably. Given how much more time cohort 2 has before their first meetings. I'm not overly concerned that this would be a problem. We can focus on cohort 1 for the time being.

**Comment by zachlatta** [comment]
Sounds good to me.

On Fri, Aug 28, 2015 at 9:55 AM, David Fontenot <notifications@github.com>
wrote:

> Amy is out of the country for another few days. Would anyone be opposed to
> starting the Group Chat for Cohort 2 next week when she gets back?
>
> That would make the call referenced in #114
> <https://github.com/hackedu/hackedu/issues/114> happen next weekend
> probably. Given how much more time cohort 2 has before their first
> meetings. I'm not overly concerned that this would be a problem. We can
> focus on cohort 1 for the time being.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/113#issuecomment-135831492>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
Amy is on vacation til Tuesday. Starting this after she gets back.

**Comment by hellyeah** [comment]
@zachlatta do you want to take cohort 2 also?

**Comment by zachlatta** [comment]
Yeah, I'm happy to take this.

On Mon, Aug 31, 2015 at 11:41 AM, David Fontenot <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> do you want to take cohort 2
> also?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/113#issuecomment-136459939>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
Waiting on:

- https://github.com/hackedu/labs-private/issues/6#issue-104748563
- https://github.com/hackedu/labs-private/issues/7#issue-104749228

**Comment by jonleung** [comment]
Assigning back to @zachlatta as discussed in [this meeting](https://github.com/hackedu/hackedu/blob/be402c47456d74ffcec238910b207d3705213a85/meta/labs/meetings/15-09-03_who_writes_the_initial_playbook.md#conclusion)

**Comment by zachlatta** [comment]
Done! https://www.messenger.com/t/1134475229901413

**Comment by jonleung** [comment]
:+1:
