### ISSUE TITLE
Schedule initial call with Labs cohort 2

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#114]

**Comment by jonleung** [comment]
Assigning this back to @zachlatta as discussed in [this meeting](https://github.com/hackedu/hackedu/blob/be402c47456d74ffcec238910b207d3705213a85/meta/labs/meetings/15-09-03_who_writes_the_initial_playbook.md#conclusion)

**Comment by zachlatta** [comment]
Sent out a Doodle link to them in the chat, waiting on it to be filled out by everyone.

**Comment by jonleung** [comment]
It seems that only one person has filled out the Doodle. Perhaps individually messaging people might help?

**Comment by jonleung** [comment]
Also adding more times for Monday and Tuesday may be helpful as well.

**Comment by zachlatta** [comment]
Yup, I started PMing people individually and set some times for tomorrow
and Thursday. Going to pester them to no end until everyone fills it out.

On Sat, Sep 5, 2015 at 10:37 AM, Jonathan Leung <notifications@github.com>
wrote:

> Also adding more times for Monday and Tuesday may be helpful as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/114#issuecomment-137980252>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Everyone filled out the form and I've confirmed a time. Going to ping them each individually to let them know about the time.

**Comment by zachlatta** [comment]
Just confirmed it with everyone.
