### ISSUE TITLE
Plan initial Labs cohort calls

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#115]
Need to set expectations and, most importantly, get them talking.

@zachlatta mentioned that everyone should do a PR while on the call, so that everyone is on even ground from the start and we set a precedent of contributing upstream. 

Additionally, everyone should be heavily encouraged to do the same PR walkthrough with the rest of the leadership team. Would be cool if this was somehow tied to adding their individual identities to a document in the actual playbook.

**Comment by zachlatta** [comment]
I'm thinking that we could have a list of everyone who's in Labs in the
repository and they could each submit a pull request to add themselves to
the list. We'd need to be _super_ diligent when merging their pull requests
to avoid merge conflicts.

Perhaps they could also link their personal sites in this as well?

On Thu, Aug 27, 2015 at 3:19 PM, David Fontenot <notifications@github.com>
wrote:

> Assigned #115 <https://github.com/hackedu/hackedu/issues/115> to
> @zachlatta <https://github.com/zachlatta>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/115#event-394530984>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
We should change this issue to duplicate since we created separate issues for cohort 1 and 2.

**Comment by zachlatta** [comment]
Closing in favor of #112 and #114.
