### ISSUE TITLE
Get club fair and first meeting dates from Labs Clubs

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#116]
I'm updating these dates in the [Temporary hackEDU Summer 2015 Clubs Spreadsheet](https://docs.google.com/spreadsheets/d/1Q6E36NK7N_mKp_LJwMW-P3KUZXPsHQTJWyoyKvrneuc/edit#gid=165578603).

**Comment by jonleung** [comment]
I'm currently blocking on getting the dates for the club fair and first club meeting from

- Tejas
- Harrison
- Jevin

because I don't know them.

FYI I'm recording them [here](https://docs.google.com/spreadsheets/d/1Q6E36NK7N_mKp_LJwMW-P3KUZXPsHQTJWyoyKvrneuc/edit#gid=165578603): 

/cc @zachlatta @hellyeah

**Comment by hellyeah** [comment]
Harrison is on IRC. Just messaged Jevin. @zachlatta can you get dates from Tejas?

**Comment by zachlatta** [comment]
Done. His school doesn't have a club fair and his first meeting will
probably be the week of September 7th.

On Fri, Aug 28, 2015 at 3:47 PM, David Fontenot <notifications@github.com>
wrote:

> Harrison is on IRC. Just messaged Jevin. @zachlatta
> <https://github.com/zachlatta> can you get dates from Tejas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/116#issuecomment-135905241>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
Jevin: "18th/19th and 25th/26th are dates in September we are thinking about, just had a chat today actually!"

**Comment by jonleung** [comment]
@hellyeah, are they doing any kind of club fair?

**Comment by jonleung** [comment]
I'm waiting on https://github.com/hackedu/labs-private/issues/5#issue-104747752

@zachlatta, can you find out when Tejass' club fair is?

**Comment by jonleung** [comment]
Oops, I just realized that [Tejas doesn't have a club fair](https://github.com/hackedu/hackedu/issues/116#issuecomment-136070164)

Closing this issue now that it is complete.
