### ISSUE TITLE
Create brief outline for how club leaders should introduce themselves in FB Group

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#117]
Blocking #108 

@jonleung lets chat about this at some point today

**Comment by jonleung** [comment]
@hellyeah, there's some stuff I need to finish beforehand. Ping me on IRC when you want to chat about it.

**Comment by hellyeah** [comment]
The main goal is to immediately lift up something about that person or their club that sparks discussion. I'm trying to think of a single question that would do this effectively.

Other things we might want to have people mention:
--school
--location
--link to club site, manifesto, or medium "hello, world" post

**Comment by zachlatta** [comment]
What about something that the leader has built recently?

On Fri, Aug 28, 2015 at 9:49 AM, David Fontenot <notifications@github.com>
wrote:

> The main goal is to immediately lift up something about that person or
> their club that sparks discussion. I'm trying to think of a single question
> that would do this effectively.
>
> Other things we might want to have people mention:
> --school
> --location
> --link to club site, manifesto, or medium "hello, world" post
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/117#issuecomment-135830106>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
I like that. It makes it really personal. Have all of our leaders built something?

**Comment by hellyeah** [comment]
What if everyone just shared their personal website? If we're making personal websites a requirement for members, then it should probably be something the leaders do beforehand.

@jonleung "What if they don't have a personal website?" 

I agree with John. I don't want to add a barrier to entry but I think we could find a way to make this low enough.

**Comment by jonleung** [comment]
From IRC:

3:01:54 PM <•jonl> dfont, thoughts on making and communicating the intro post guidelines to the labs clubs top priority?
3:02:23 PM <•jonl> Jeremy & Teagan are asking about designing posters, I want to be able to redirect them to the Facebook group.
3:02:37 PM <•jonl> Can you take lead on onboarding the labs club leaders into the facebook group asap?

/cc @hellyeah

**Comment by hellyeah** [comment]
https://www.facebook.com/groups/1501083703514499/permalink/1626147637674771/

**Comment by paked** [comment]
Just for future reference, at **some** point. Maybe when all of the current conversation dies down a "What have your recently been working on?" post might be beneficial to jump start interaction again.
