### ISSUE TITLE
Revamp the description on hackEDU Leaders Facebook Group

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#118]
https://www.facebook.com/groups/1501083703514499

**Comment by zachlatta** [comment]
Thoughts on:

The community of people leading Hack Clubs around the world.

Code of conduct: https://example.com

New members comment on this post: https://facebook.com/examplepost

On Fri, Aug 28, 2015 at 5:14 PM, David Fontenot <notifications@github.com>
wrote:

> https://www.facebook.com/groups/1501083703514499
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/118>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#301
