### ISSUE TITLE
Make sure that shipit.hackedu.us includes a dropdown with every high school we have

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#119]
**EDIT**: Currently, this list is not comprehensive:

![image](https://cloud.githubusercontent.com/assets/654941/9564835/d2524b48-4e67-11e5-8d55-2ff004d171fd.png)

/cc @zachlatta

**Comment by paked** [comment]
Glenaeon Rudolf Steiner School is not there, as well as Armijo High School, Lowell High School and USC Hybrid High School. Those are the ones from the labs list, I could probably pull more from the Facebook group.

But really, I don't think that it makes much sense currently to have this at all? It seems kind of contradictory to the "Use our playbook anywhere" model which we (you guys? us?) are going for.

**Comment by jonleung** [comment]
^ @paked, hmmmm, good point! Zrl. Thoughts on making other a default?

**Comment by zachlatta** [comment]
I agree with you @paked that it's certainly not the most inclusive choice
to have a dropdown of clubs. I'd love to add an option later so anyone can
create clubs (do note: the name of the school they choose is translated
into the directory name generated by their pull request).

I think it makes the most sense to just update this list to our existing
clubs for now and then defer making it possible for anyone until later.
I've created hackedu/shipit#40 to track this.

On Tue, Sep 8, 2015 at 9:59 AM, Jonathan Leung <notifications@github.com>
wrote:

> Assigned #119 <https://github.com/hackedu/hackedu/issues/119> to
> @zachlatta <https://github.com/zachlatta>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/119#event-403878252>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Closing in favor of hackedu/shipit#40.
