### ISSUE TITLE
You should have all physical and digital materials open and layed out.

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#12]
- There is very limited time in a club meeting.
- Moreover, the more time it takes to do something in the club, members get distracted and the moment of the club meeting can be lost
- Therefore, if you can either do something X either in the club meeting or before the club meeting, opt to do it before the club meeting
- Example, if you have a demo app you want to show someone, opt for opening this in a tab before you enter the club meeting vs finding it and opening it during the club
- By having all these things open, it will trigger what you have to do so you won't forget

**Comment by zachlatta** [comment]
Can you give this issue a more descriptive/specific title? I'm not quite sure what this means just from the title.

**Comment by zachlatta** [comment]
Ah, now that I'm looking at the web interface, I see.

Perhaps this would be better suited for a file in the repo? Issues may not be the best place for content.

**Comment by jonleung** [comment]
@zachlatta, I opened an issue instead of a file because you can't comment on a file, only a file *change*

Any suggestions on how to do this would be helpful!

**Comment by zachlatta** [comment]
This is true, but is this something that warrants discussion? If someone wants to change something, they can open an issue or a PR.

Is GitHub issues the best place to store information/data?

**Comment by jonleung** [comment]
Yeah, not sure how to do this better though.

**Comment by zachlatta** [comment]
> Perhaps this would be better suited for a file in the repo?

**Comment by zachlatta** [comment]
Just following-up on this.

**Comment by jonleung** [comment]
Close
ᐧ


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment]
What?

**Comment by jonleung** [comment]
Closed, trying to close the issue. A.k.a Skip
ᐧ


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment]
So do you agree that "Perhaps this would be better suited for a file in the repo?" and we should close this issue? I'm confused.

**Comment by jonleung** [comment]
I don't know
ᐧ


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment]
What? Why are you trying to close the issue if you don't know whether it's resolved or not?

**Comment by jonleung** [comment]
I don't think it's worth spending time discussing this right now. What do I do with those kinds of issues?

**Comment by zachlatta** [comment]
Let's close it for now.
