### ISSUE TITLE
Clean up migrated club playbook materials

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#14]
I went ahead and moved the club playbook materials from https://github.com/hackedu/meta to here in 22c6cfbc201b7a93da3f5505e8e15564240b21b9.

Can you go through these and reorganize/remove things as needed?

**Comment by jonleung** [comment]
Cool, will do @zachlatta. Closing issue even though I didn't do it yet because it will eventually new done.

**Comment by zachlatta** [comment]
What's the point of closing this if it's not resolved and part of the sprint?

**Comment by jonleung** [comment]
I don't remember committing to this for this week, I want to table this and focus on the more important things

**Comment by zachlatta** [comment]
Alright, sounds good. Adding to backlog.

> What's the point of closing this if it's not resolved and part of the sprint?

**Comment by jonleung** [comment]
Closed because it is no longer relevant
