### ISSUE TITLE
Create issue for every Labs team in secret repo

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#141]

**Comment by jonleung** [comment]
Let's create these as needed (i.e. whenever you interact with a club organizer and you think it's worthwhile that the rest of the team know, update / create an issue for it).

That's what I've been doing for now. 

See:
https://github.com/hackedu/labs-private/issues


Thoughts @hellyeah and @zachlatta?

**Comment by hellyeah** [comment]
Create bullet point in the description for every Leader

**Comment by jonleung** [comment]
As discussed on Friday, September 4th, this issue has been reassigned to @hellyeah .

In order for this issue to be resolve:

- [ ] every Labs club has an associated issue
  - [ ] with the name of their school listed
  - [ ] with all the names of every lab director in the description of the issue

**Comment by hellyeah** [comment]
Moved to hackedu/clubs/issues

hackedu/clubs/issues#1
hackedu/clubs/issues#2
hackedu/clubs/issues#3
hackedu/clubs/issues#4
hackedu/clubs/issues#5
hackedu/clubs/issues#6
hackedu/clubs/issues#7
hackedu/clubs/issues#8
hackedu/clubs/issues#9
hackedu/clubs/issues#10
hackedu/clubs/issues#11
hackedu/clubs/issues#12

**Comment by zachlatta** [comment]
Can we close this?
