### ISSUE TITLE
Create issues for every Labs Leader

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#142]

**Comment by jonleung** [comment]
@hellyeah, should this issue be in the private Labs repo (https://github.com/hackedu/labs-private)

**Comment by jonleung** [comment]
Wait, @hellyeah, are these duplicates (https://github.com/hackedu/hackedu/issues/141)?

**Comment by jonleung** [comment]
@hellyeah, poke ^

**Comment by zachlatta** [comment]
Duplicate of #141.
