### ISSUE TITLE
Send hand-written letter to confirmed hackEDU lab directors

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#148]
/cc @zachlatta

**Comment by zachlatta** [comment]
I created #149 to track getting the addresses and phone numbers from all of the leaders. This is currently blocking on that.

**Comment by jonleung** [comment]
All the letters are written, here are the remaining tasks:

- [ ] Seal the envelopes with water and wax
- [ ] Buy appropriate stamps
- [ ] Mail them

**Comment by jonleung** [comment]
Done.

**Comment by zachlatta** [comment]
![](https://media.giphy.com/media/143vPc6b08locw/giphy.gif)
