### ISSUE TITLE
Collect phone numbers and addresses from all club leaders

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#149]
I've sent out http://goo.gl/forms/WhGVza2W4G to all of the Lab Directors taking point on communication in cohort 2. I asked them to fill it out by the end of the day.

Waiting on their responses.

**Comment by jonleung** [comment]
@zachlatta, do we need to remind people who have not filled this out to fill it out?

**Comment by zachlatta** [comment]
Got responses from everyone I sent it to. Just reminded the people that I only got one response from to also ping their co-leads again.

**Comment by jonleung** [comment]
I removed the `blocking` because it seems like this task is no longer blocking. Is that accurate?

**Comment by zachlatta** [comment]
Done!
