### ISSUE TITLE
Example club constitution

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#15]
Formerly hackedu/meta#23.

---

As mentioned by @MaxWofford in the old issue, it'd be great if we had an example club constitution. We could start with @raphaelrk's (https://docs.google.com/document/d/1jvuNDaJASLbuxoc2Q6NepYHOKejy0Az-Z6ikAhpYxlM/edit).

**Comment by zachlatta** [comment]
Are we holding off on this for now?

**Comment by MaxWofford** [comment]
@zachlatta @jonleung What is an actionable way to proceed with this?

**Comment by MaxWofford** [comment]
@zachlatta Do we need this for our Labs clubs?

**Comment by jonleung** [comment]
@MaxWofford we might need it for some of our labs programs. Perhaps close this until we need one?

**Comment by MaxWofford** [comment]
@jonleung Sounds good
