### ISSUE TITLE
Create section headers for first club meeting and club fair guides

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#150]

**Comment by jonleung** [comment]
@hellyeah and I had a conversation about how we might revise how Lab Directors will initially contribut to the playbook. We realized that we didn't like the precedent that we set by us writing up a detailed guide for the first club meeting. We came to the conclusion that it may make more sense to create two empty sections (one for the first club meeting and one for the club fair) that lab directors could individually fill out. Once the headers are created, we can post in the group chats asking people to help fill it out.

/cc @zachlatta

**Comment by jonleung** [comment]
Closing because this is now addressed by #151
