### ISSUE TITLE
Write the language that communicates what lab directors need to do before and after each club meeting

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#151]
**Task**: Write the language that communicates what lab directors need to do before and after each club meeting

**Here are the expectations for Lab Directors that we discussed during the meeting:**

> - Before every meeting, each lab club will
>   - submit a pull request detailing what they are planning for their club
>     meeting.
> - After each meeting _**by the end of the day**_, each lab club will
>   - write a medium blog post with post-mortem detailing
>     - what went well in the club
>     - what didn't go well in the club
>     - suggestions for what other club leaders should and shouldn't try
>   - make a pull request to append the medium blog post to their initial planning
>     file
> 
> - Note: All in on GitHub for planning notes and post meeting notes UNLESS, we
>   notice a huge delay OR low quality for the post meeting notes.

_^ exerpted from [the meeting notes](https://github.com/hackedu/hackedu/blob/be402c47456d74ffcec238910b207d3705213a85/meta/labs/meetings/15-09-03_who_writes_the_initial_playbook.md#conclusion)_

**Also, here are some thoughts I had after the club meeting:**

- It was not clear *when* they need to submit the pull request before the
  meeting.
  - Jonathan suggests they should do it at least **3 days** before a
    club meeting so that other leaders have ample time to give them
    feedback on it
- Also Jonathan thinks that it is a good idea for lab directors to take
their meeting plans and the post-mortem blog posts and post them
in the hackEDU leaders group as well as their cohort's chat.
  - Instead of just linking it, they may want to provide a quick TLDR
    so that other leaders can engage with the content without having
    to open the link.

Feel free to ping me to discuss the above!

**After the task is complete**

When you are done, please ping @zachlatta so he can use this language to communicate this to lab directors. Zach will need to do this to complete #153

**Comment by jonleung** [comment]
@hellyeah, also because some people have seen the playbook for club fair already (I sent it to them because they asked for it) and also to be transparent, do you think we should provide context explaining *why* we are moving away from a top down approach of the playbook? I.e. should we explain why we chose to move away from **us** writing everything to **them** writing weekly posts and giving each other feedback?

**Comment by hellyeah** [comment]
"Most high school clubs just wing it. Creating a plan for your meetings not only makes your team seem organized but also provides a much better experience for your club members.  

As a Labs Director, you should leverage your entire cohort to plan the best club meetings. We created a planning file for you. Feel free to structure your plan any way you'd like: [link]

Send a PR with the plan for your first meeting and share it with your Labs Cohort so they can give you ideas and feedback. It's ok if you don't have everything figured out. Note the missing gaps in your plans so that your team of Labs Directors can help you fill them in."

**Comment by hellyeah** [comment]
"When we threw the first MHacks, we gave hundreds of students a great experience. This is how we were able to do that..."

**Comment by hellyeah** [comment]
"We thought about the hacker's experience from the moment they stepped off the bus every step of the way..."

**Comment by hellyeah** [comment]
"When we threw the first MHacks, we give 500 students the experience of their lives. 

What separated us from every other hackathon is that we planned the hacker experience every step of the way. You can do this with your clubs too. 

As a Labs Director, you should leverage your entire cohort to plan the best club meetings. Feel free to structure your plan any way you'd like. Here's a basic template to get you started: [link]

Send a pull request (PR) with the plan for your first meeting and share it with your Labs Cohort so they can give you ideas and feedback. It's ok if you don't have everything figured out."

**Comment by hellyeah** [comment]
@zachlatta did you want me to take lead on this? If so, what do you think is the best course of action? Messaging the group chat?

**Comment by zachlatta** [comment]
My apologies for the delay.

@hellyeah: it'd be great if you could message the group chat about this, I'd encourage you to make the new expectations clearer though. Right now it reads closer to a "general suggestion" than "this is what you're going to be doing from now on", at least to me.

**Comment by jonleung** [comment]
@hellyeah, I was envisioning something in addition to this, I don't think I clearly articulated it though. I'm happy to take the next stab at this, let's correspond over IRC?

**Comment by jonleung** [comment]
I won't get to it until tomorrow though : /

**Comment by jonleung** [comment]
@hellyeah, just an FYI that I'm about to start collaborating on this issue with you!

**Comment by jonleung** [comment]
@hellyeah @zachlatta: this is my first draft:
https://gist.github.com/jonleung/a4732532015847ef9405

**Comment by zachlatta** [comment]
I think that's too long.

Any way we can shoot for half of the length, or less?

**Comment by zachlatta** [comment]
Assigning @jonleung because @hellyeah is MIA at PennApps.

**Comment by jonleung** [comment]
@zachlatta, this is an updated version:
https://gist.github.com/jonleung/a4732532015847ef9405

**Comment by prophetorpheus** [comment]
@jonleung: can you post the version we came up with together last night?

On Sun, Sep 6, 2015 at 1:20 PM, Jonathan Leung <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta>, this is an updated version:
> https://gist.github.com/jonleung/a4732532015847ef9405
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/151#issuecomment-138123224>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Uhh, not sure how that became from @prophetorpheus. This is Zach.

On Mon, Sep 7, 2015 at 9:13 AM, Prophet Orpheus <notifications@github.com>
wrote:

> @jonleung: can you post the version we came up with together last night?
>
> On Sun, Sep 6, 2015 at 1:20 PM, Jonathan Leung <notifications@github.com>
> wrote:
>
> > @zachlatta <https://github.com/zachlatta>, this is an updated version:
> > https://gist.github.com/jonleung/a4732532015847ef9405
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hackedu/hackedu/issues/151#issuecomment-138123224>.
> >
>
>
>
> --
> Zach Latta
> hackEDU | zach@hackedu.us
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/151#issuecomment-138333542>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
https://gist.github.com/jonleung/2b024e09264d8de25521

**Comment by zachlatta** [comment]
Sounds good! Want to submit a pull request to add this to the Labs folder?

On Mon, Sep 7, 2015 at 11:37 AM, Jonathan Leung <notifications@github.com>
wrote:

> https://gist.github.com/jonleung/2b024e09264d8de25521
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/151#issuecomment-138354388>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta, perhaps later, don't feel this is too high leverage right now.
