### ISSUE TITLE
Clearly communicate new expectations to Lab Directors

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#153]
As discussed in [this meeting](https://github.com/hackedu/hackedu/blob/be402c47456d74ffcec238910b207d3705213a85/meta/labs/meetings/15-09-03_who_writes_the_initial_playbook.md#conclusion).

Take the language that Dave writes in #151 and the new workflow you setup in #152 and communicate it with club leaders.

Please see #151 and #152 for details.

**Comment by jonleung** [comment]
@hellyeah, see my comments in #151

**Comment by jonleung** [comment]
Since I've taken #151, I can take this one as well.

**Comment by jonleung** [comment]
Blocking on #151

**Comment by jonleung** [comment]
Although this task is no longer blocking on #161,
It is blocking on #114 because we can't message the group until people respond to the Doodle poll.

Also, the new languaging is conveyed in #151

**Comment by jonleung** [comment]
@zachlatta is going to bring this up in the cohort 2 call today and so I'm closing this issue.

**Comment by zachlatta** [comment]
Done!
