### ISSUE TITLE
Labs Leaders planning/post-mortem PR if they had first meeting last week

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#169]
Identify which leaders have a meeting this week.

**Comment by hellyeah** [comment]
- [ ] Gemma
  - [ ] Planning: 
  - [ ] Recap: 
- [ ] Bogdan: 
  - [ ] Planning:
  - [ ] Recap: https://github.com/CHE-CS/hackedu/blob/master/case_studies/cherry_hill_high_school_east/02_first_meeting/recap.md

**Comment by jonleung** [comment]
@hellyeah, I'm closing this issue because it seems that according to the above comment, @gemmabusoni and @Bogidon have both submitted a case study.

**Comment by Bogidon** [comment]
recap... 😬

**Comment by zachlatta** [comment]
Reopening due to needing @Bogidon's recap.

**Comment by Bogidon** [comment]
😖 I'll write it

**Comment by hellyeah** [comment]
Failed to get planning and still waiting on recap to be merged in from gemma. Going to close this bc its stale now so we can focus on contributions moving forward.
