### ISSUE TITLE
Ship Twilio workshop

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#171]
- [ ] get it on master
- [ ] add facilitation guidelines

**Comment by jonleung** [comment]
I'm finished a draft of the Twilio signup process:

https://github.com/hackedu/hackedu/blob/jon-remote-control/playbook/workshops/remote_control/twilio_signup_instructions.md

**Comment by jonleung** [comment]
Submitted #234 and assigned @paked to review!

**Comment by paked** [comment]
@jonleung :heart:

**Comment by paked** [comment]
![https://33.media.tumblr.com/65a067e10ac1568850bc4ca82651ace5/tumblr_no11miAcTm1u4zzcpo1_500.gif] :+1:
