### ISSUE TITLE
Make fontebot for #hackEDU irc

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#172]
Talk to hardmath and max

**Comment by MaxWofford** [comment]
@hellyeah What does this issue mean?

**Comment by zachlatta** [comment]
Going to move this to `hackedu/meta` because it doesn't have to do with our existing clubs.

I'd bias towards having this be a personal note, rather than an organization issue.

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#133
