### ISSUE TITLE
hackEDU Meetup at MHacks

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#174]
What club leaders will be at MHacks?

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#134

**Comment by zachlatta** [comment]
Going to move this to `hackedu/meta` because it's not directly applicable
to the playbook.

On Tue, Sep 8, 2015 at 10:08 AM, David Fontenot <notifications@github.com>
wrote:

> What club leaders will be at MHacks?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/174>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us
