### ISSUE TITLE
Isn't "post-mortem" a bit macabre?

### ISSUE THREAD

**Issue by Bogidon** [hackedu/hackedu#176]
The term `post-mortem` used to indicate post-event reflections for the [case_studies](https://github.com/hackedu/hackedu/tree/master/case_studies) seems a bit macabre, it's most popular definition being "happening after death." For me at least, being a Romanian speaker (which is close to latin), I flinch when I read it :confused:

Maybe `post-event` or `after-event` would be more appropriate.

**Comment by paked** [comment]
:+1:. I would suggest maybe `pre-event` and `post-event?

**Comment by hellyeah** [comment]
Macabre?

**Comment by hellyeah** [comment]
Just looked it up.

@jonleung I agree with them. How about "planning" and "recap"

**Comment by jonleung** [comment]
@Bogidon Thanks for making the issue!

Thoughts on @hellyeah's `recap`

/cc @zachlatta

**Comment by zachlatta** [comment]
Recap sounds good.

On Wed, Sep 9, 2015 at 10:34 AM, Jonathan Leung <notifications@github.com>
wrote:

> @Bogidon <https://github.com/Bogidon> Thanks for making the issue!
>
> Thoughts on @hellyeah <https://github.com/hellyeah>'s recap
>
> /cc @zachlatta <https://github.com/zachlatta>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/176#issuecomment-138985551>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by Bogidon** [comment]
I like 'recap'!

Also, I believe the terms 'pre-mortem' and 'post-mortem' are used somewhere in the hack-camp repo. I can raise an issue there in a little bit if you'd like.



On Wed, Sep 9, 2015 at 10:34 AM -0700, "Jonathan Leung" <notifications@github.com> wrote:












@Bogidon Thanks for making the issue!



Thoughts on @hellyeah's recap



/cc @zachlatta

**Comment by jonleung** [comment]
@Bogidon, would you be interested in submitting a pull request for this change?

**Comment by Bogidon** [comment]
I'll do it.

**Comment by Bogidon** [comment]
Um so I messed up a little. I renamed `post-mortem` to `recap` (everywhere), but I accidentally included my commit adding _my_ recap.md in the `rename-post-mortem-to-recap` branch. Also, there's a merge conflict somewhere but it shouldn't be too bad... although I can't see where it is.

**Comment by Bogidon** [comment]
Here's the link to the pull request: https://github.com/hackedu/hackedu/pull/187

**Comment by jonleung** [comment]
Hell yeah @Bogidon! @zachlatta will work with you to merge this pull request in!

**Comment by zachlatta** [comment]
Closed by #187.
