### ISSUE TITLE
Create feedback forms for every labs leader for every meeting

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#184]
Here is an [example feedback form](https://docs.google.com/forms/d/1duF1KhZML87ri-HrDwwZeWOnPWoVWgl9Kt-idlnmKCI/viewform).

Here are the [awesome responses](https://docs.google.com/spreadsheets/d/1bdWkKmBfaYiPBOMjkkG7Gpz3oq6mYxepAatN6HMnTJI/edit#gid=50885854) that we got!

/cc @zachlatta @hellyeah

**Comment by zachlatta** [comment]
I created a folder for Cherry Hill East in
https://drive.google.com/drive/u/0/folders/0B34YNYNQ6z3YfjgwcXNjaTVQb2Z0cUFuWjBDTDN3SGU4SlJXeWwxRV9MWW14ZTBFbklUVDg.
Let's create other folders in that same directory.

On Wed, Sep 9, 2015 at 4:20 PM, Jonathan Leung <notifications@github.com>
wrote:

> Here is an example feedback form:
> https://docs.google.com/forms/d/1duF1KhZML87ri-HrDwwZeWOnPWoVWgl9Kt-idlnmKCI/viewform
>
> Here are the awesome responses that we got!
>
> https://docs.google.com/spreadsheets/d/1bdWkKmBfaYiPBOMjkkG7Gpz3oq6mYxepAatN6HMnTJI/edit#gid=50885854
>
> /cc @zachlatta <https://github.com/zachlatta> @hellyeah
> <https://github.com/hellyeah>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/184>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
These have all been put into https://drive.google.com/drive/u/0/folders/0B34YNYNQ6z3YfjgwcXNjaTVQb2Z0cUFuWjBDTDN3SGU4SlJXeWwxRV9MWW14ZTBFbklUVDg

**Comment by zachlatta** [comment]
Can you make sure the form responses are going to the `Feedback` spreadsheet in the same directory?

![recorded](https://cloud.githubusercontent.com/assets/992248/9822476/8e3fec18-5875-11e5-8b2e-9e3895251087.gif)

Seems like responses are currently turned off.

**Comment by MaxWofford** [comment]
@zachlatta All the form responses are going into `Feedback` in the same directory. I just went through all the forms and turned on responses for everyone except Cherry Hill East.
