### ISSUE TITLE
Will ship a medium blogpost on how he got an internship offer

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#19]
So excited for this!

**Comment by zachlatta** [comment]
Perhaps we could also have this in a Markdown file in the repo?

**Comment by Bogidon** [comment]
I'm in! I will publish to Medium, but can add a markdown version to the repo as well.

**Comment by zachlatta** [comment]
Perfect. Let's plan on both.

**Comment by jonleung** [comment]
@ZachLatta, not sure if it makes sense to duplicate efforts here because
wouldn't it be great if the conversations took place in one place, i.e.
medium?
ᐧ


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment]
Will there be conversation associated with every post? It'd be nice to
link to as few external things as possible because links die over time.

**Comment by MaxWofford** [comment]
@jonleung Is this still a high leverage activity?

**Comment by zachlatta** [comment]
I vote for closing for now.

**Comment by MaxWofford** [comment]
@zachlatta Ok, I'll bring this up to @jonleung irl, and close the issue within 3 hours if there are no updates.

**Comment by zachlatta** [comment]
Your GitHub issues skills are on point.

**Comment by jonleung** [comment]
@zachlatta, feel free to close
ᐧ


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083
