### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#2]
In IRC, @JacobEdelman said:

> zrl: I think what I'd suggest is rebranding club-in-a-box to indicate its a place for discussion of all club related things, rather than just setting up a club, a specific folder of it could serve as a getting started guide. In general it could serve as a sort of collaborative wiki where any permanent content that comes out of discussions in the issues

This is the thread for discussing that.

**Comment by MaxWofford** [comment]
:+1: for a collaborative wiki. That's seems like a great format for this.

**Comment by zachlatta** [comment]
Just to be explicit, I'm thinking that people would create/edit files in
the main repo through PRs, not necessarily using GitHub wikis. What are
your thoughts?

**Comment by JacobEdelman** [comment]
Same here, although the repo might end up being treated like a collaborative wiki I imagine.

**Comment by zachlatta** [comment]
Yeah, agreed. ^

**Comment by jonleung** [comment]
Agreed to everything

**Comment by zachlatta** [comment]
Great, once hackedu/docs#27 is closed we can close this as well and move forward.

**Comment by zachlatta** [comment]
Renamed!
