### ISSUE TITLE
Syncing up with Labs Leaders

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#200]
I'm syncing up with some of Labs Leaders to figure out things like:

- what's happening
- when their next meeting is
- what they're thinking about doing in that meeting
- noting when their club meetings and such are in working columns

All of my notes will be documented in the issues in hackedu/clubs

**Comment by zachlatta** [comment]
Isn't @hellyeah already doing this?

**Comment by jonleung** [comment]
@zachlatta didn't we decide that it was ok if we both did this? Currently the data for club leaders dates are not created yet and I chatted with @hellyeah to and I'm going to transfer the dates from the old spreadsheet to the new spreadsheet. I'm moving forward with the assumption that any communication with labs leaders is documented [in here](https://github.com/hackedu/clubs/issues)

**Comment by jonleung** [comment]
Closing because @hellyeah is doing it this week.
