### ISSUE TITLE
Get more high schoolers into college hackathons

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#207]

**Comment by paked** [comment]
:+1:. Keep me in the loop.

**Comment by jonleung** [comment]
Moved this into "Ideas"

**Comment by zachlatta** [comment]
Can we turn this into something a bit more actionable?

On Tue, Sep 15, 2015 at 9:07 AM, Jonathan Leung <notifications@github.com>
wrote:

> Moved this into "Ideas"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/207#issuecomment-140445478>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
@zachlatta yes. We definitely should. I'm going to close this. I'll focus more on this goal next semester.
