### ISSUE TITLE
Create GitHub Issues for problems with 2nd workshop

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#208]
You mentioned that there were some problems with the second workshop you wanted to create GitHub Issues for.

**Comment by paked** [comment]
@jonleung @zachlatta. I thought we were not doing the sequential workshop model? Or have things changed again?

**Comment by jonleung** [comment]
@paked, we ideally wouldn't be doing a sequential workshop model but at least for now, it's probably going to look that way because I'm only creating one workshop per week. However @Bogidon is creating some cool workshops that others would be able  to use as well!

**Comment by jonleung** [comment]
I created the following issues:

#235 
#236 
#237 
#238 
#239 
#240 

I also made the [`workshop` label](https://github.com/hackedu/hackedu/labels/workshop)

And the [`Remote Control Workshop` Milestone](https://github.com/hackedu/hackedu/milestones/Remote%20Control%20Workshop)

Thoughts @zachlatta @paked?
