### ISSUE TITLE
Collect data from leaders and make sure club leaders have successors

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#21]
Reach out to all of our club leaders and collect the following data:

* Is there a successor?
* Do we know them?
* Where are you going to college?
* Testimonial for hackEDU
* NPS for hackEDU
* Biggest problems they've faced as a club leader
  * Validate the assumption that the biggest thing is curriculum

Additionally, have all of the club leaders make a PR to add themselves to a club leaders CSV with their name and info.

**Comment by zachlatta** [comment]
Revising this task...

Instead of collecting all of that data, just make sure that everyone, if needed, has a successor (I'll leave anything else to your discretion, just make note of the work you're doing in this issue).

**Comment by MaxWofford** [comment]
I'm not getting a ton of responses through fb. Do you have the contact info of many of these leaders?

**Comment by MaxWofford** [comment]
@jonleung @zachlatta I'll be sending you two a list of everyone who hasn't responded. Could you try getting in contact with them?

**Comment by zachlatta** [comment]
Have you tried pinging them to follow-up?

**Comment by MaxWofford** [comment]
Closing this because no longer relevant.
Status: all updated club leaders are in the airtable. Empty columns are clubs that I couldn't reach multiple times.
