### ISSUE TITLE
Message club leaders to ask them for feedback on pull request

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#210]
Keep it brief and below 50 lines

**Comment by jonleung** [comment]
I still need to make Max's fixes.

**Comment by jonleung** [comment]
Fixed all of @MaxWofford's comments.

Waiting for Lab directors to look at #224

**Comment by zachlatta** [comment]
Status on this?

**Comment by jonleung** [comment]
Will be messaging club leaders to get their feedback on this to see if we can start a discussion in the pull request.

**Comment by jonleung** [comment]
Decided not to do this.
