### ISSUE TITLE
Document the expectations of Labs Directors regarding their Github privileges

### ISSUE THREAD

**Issue by paked** [hackedu/hackedu#212]
Currently the Labs Directors have been given contributing status. It is unclear as to what we should be using our status for.

For example:

* If a PR comes up which looks merge-able, what happens? Should the Labs Director merge it?
* There are unassigned issues, should someone claim them?

**Comment by MaxWofford** [comment]
Thoughts @hellyeah @jonleung @zachlatta ?

I can cover this in the meeting about PRs on Thursday, but it might be slightly out of scope.

**Comment by paked** [comment]
@MaxWofford @jonleung How is this coming along?

**Comment by MaxWofford** [comment]
@paked Everyone on the contributing team can assign themselves to unassigned issues.

PRs will still be merged in by the core team until [markcop](https://github.com/hackedu/markcop)'s test coverage is higher.

**Comment by paked** [comment]
Sounds good to me.

**Comment by MaxWofford** [comment]
This issue can be closed when this is documented in our `CONTRIBUTING.md`

**Comment by zachlatta** [comment]
Going to move this to our backlog in ZenHub.

**Comment by MaxWofford** [comment]
Closing this issue for now. It will be revisited when I start working on increasing club leader collaboration.
