### ISSUE TITLE
Recap MHacks with a Medium post

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#218]
An MHacks meetup was organized in issue #174.

This is the issue to document that meetup with a Medium post.

**Comment by ssun098** [comment]
@hellyeah will try to get this done asap

**Comment by ssun098** [comment]
@hellyeah Submitted a Medium draft.  It's preeetty bad at the moment, but could you give it a look when you're back from HtN and give feedback? Thanks!

**Comment by hellyeah** [comment]
Reviewed draft.

**Comment by hellyeah** [comment]
@ssun098 is going to iterate on the post and I'll edit and publish.

**Comment by ssun098** [comment]
@hellyeah im done I think

**Comment by hellyeah** [comment]
@ssun098 publishing later today!

**Comment by hellyeah** [comment]
Launched: https://www.facebook.com/permalink.php?story_fbid=1040798692637819&id=741805665870458

@ssun098 link your post too!

**Comment by ssun098** [comment]
https://medium.com/hack-edu/hs-hackers-meetup-at-mhacks-65a7088cf84b :smiley:

**Comment by paked** [comment]
:+1: good job!

**Comment by ssun098** [comment]
Thanks @paked!
