### ISSUE TITLE
Discuss how to share notes on clubs as we talk to them.

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#219]
cc @jonleung

**Comment by hellyeah** [comment]
Set up time with @jonleung on Monday or Tuesday to discuss how we share notes on our communication with Labs.

**Comment by jonleung** [comment]
@hellyeah one idea that I had was to just discuss the status of ever lab leader right after standups. We could go through name by name and either one of us could bring up things that we think is relevant to bring up for a given club leader.

Thoughts?

/cc @zachlatta

**Comment by jonleung** [comment]
@hellyeah can you post the notes you took on what we decided in today's meeting?

**Comment by hellyeah** [comment]
We agreed to share individual clubs notes on the issues in the clubs repo as we saw fit. We need to actually do this and keep them updated.

After standup, at 930am, @jonleung and I will be having a brief, 30 minute, meeting to discuss clubs. The expectation is that these notes are added to the clubs issues before that meeting. 

On Mondays, that meeting will be 1 hour long and we will message club leaders to start off the week.
