### ISSUE TITLE
Add all Labs Leaders to Medium publication

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#220]

**Comment by hellyeah** [comment]
Added a Medium column to http://clubs.hackedu.us

**Comment by zachlatta** [comment]
Can you make sure to include an owner and expiration date, per the README
@hellyeah?

On Thu, Sep 17, 2015 at 1:22 PM, David Fontenot <notifications@github.com>
wrote:

> Added a Medium column to http://clubs.hackedu.us
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/220#issuecomment-141216907>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#299
