### ISSUE TITLE
Actively message and respond to club leaders

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#226]
The goal of this task is to build a relationship with club leaders.

**Comment by MaxWofford** [comment]
@jonleung What do we have to do to close this issue?

**Comment by jonleung** [comment]
@MaxWofford, I believe that we may want to treat this as a weekly open issue.

Thoughts @hellyeah?

**Comment by zachlatta** [comment]
This issue doesn't sound actionable. Can you clarify @jonleung?

On Sat, Sep 19, 2015 at 8:46 PM, Jonathan Leung <notifications@github.com>
wrote:

> @MaxWofford <https://github.com/MaxWofford>, I believe that we may want
> to treat this as a weekly open issue.
>
> Thoughts @hellyeah <https://github.com/hellyeah>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/226#issuecomment-141742538>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@hellyeah, we initially were not thinking of tracking this in an issue because it didn't seem actionable. However, we decided that even though it wasn't really actionable, this was an active piece of work that you were doing and so we wanted to track it on the board. @hellyeah, do you want to clarify what this work was?
