### ISSUE TITLE
Create more folders inside of clubs' case study folder

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#227]
Every club only has two folders inside their case study folder:

> ![image](https://cloud.githubusercontent.com/assets/654941/9972812/f43b9cb2-5e1d-11e5-9ebd-bba26f8c4676.png)

We need folders for the 2nd, 3rd, 4th, club meeting.

Thoughts on making the folders for club meetings 2 through 12 now so we don't run into this problem again?

/cc @zachlatta @MaxWofford @hellyeah @paked

**Comment by paked** [comment]
I don't think creating a bunch of folders is a good idea... Perhaps have a
template folder people can clone?

I also don't like the naming scheme... But not quite sure what to do about
it.

**Comment by MaxWofford** [comment]
@jonleung Is there a reason the club leaders can't create new folders as they have meetings?

@paked On a chat with @gemmabusoni, she voiced her concerns that it was weird having `02_first_meeting`. It this along the lines of what you don't like about it?

**Comment by paked** [comment]
Yes that sounds about right.

**Comment by jonleung** [comment]
@MaxWofford I think that club leaders can totally make their own folders on their own. I believe that @zachlatta wanted to make sure that their naming scheme was consistent so that he could do batch changes to all of the notes. I personally think that being able to batch changes are not super helpful right now.

Having pre-populated folders currently leads to the issue that it's hard to tell which folders have something in them and which ones do not.

**Comment by jonleung** [comment]
@AbigailMed @amysorto @Bogidon @gemmabusoni @JevinSidhu @paked @sneharamapo @ssun @tejasmanohar @temucher @venethefifth @xeonjake, what are your guy's thoughts on:

1) What a good naming convention for the folders might be
2) Creating your own folders (we'll all need to be really careful about following the same folder naming convention) vs us creating them for you guys?

**Comment by venethefifth** [comment]
I think a good name convention would be (High School) - (What folder is) like College Park - Code for Instagram or CPHS - Code, or have the high school name with a date instead. And I think you guys creating folders would be best in the beginning and I’m sure it will soon catch on and we’d do it ourselves.

**Comment by ssun098** [comment]
If we're doing separate folders for each meeting, I think we should base it on date/content: 
`(Date)_(Purpose)_(Meeting/Event)`. 

I'm not too sure how y'all format your dates, but an example would be: 
`09-20-15_WebdevIntro_Meeting`
or 
`09-20-15_ClubFaire_Event`

I understand it may get a little chaotic though, but it'll be easier to reference if we were to search for content. Thoughts?

**Comment by Bogidon** [comment]
I'm fine with @ssun098's naming conventions. I also think that club leaders should make their own folders.

**Comment by paked** [comment]
I see no legitimate reason to automatically create folders. Especially if we are using a system like @ssun098 describes which includes metadata in the name.

**Comment by tejasmanohar** [comment]
Makes sense to me too

**Comment by zachlatta** [comment]
Yeah, I like @ssun098's suggested name format as well.

What are everyone's thoughts on the following convention for names?

YY-MM-DD_meeting_title_{event|meeting}

Examples:

- `15-09-21_portfolio_workshop_meeting`
- `15-09-15_club_fair_event`
- `15-09-02_school_fundraiser_event`

The reason I'm thinking YY-MM-DD instead of MM-DD-YY is because sorting
YY-MM-DD alphabetically will cause it to show the folders in order, while
MM-DD-YY will show them out of order.

On Sun, Sep 20, 2015 at 2:33 PM, Tejas Manohar <notifications@github.com>
wrote:

> Makes sense to me too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/227#issuecomment-141836105>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
:+1: to `YY-MM-DD_meeting_title_{event|meeting}`

**Comment by jonleung** [comment]
:+1:

**Comment by ssun098** [comment]
:+1:

**Comment by MaxWofford** [comment]
@zachlatta Can we  close this issue? It seems like club leaders can create their own folders.

> I also think that club leaders should make their own folders.

> I see no legitimate reason to automatically create folders. 

> Makes sense to me too. I think leaders can create their own folders.

**Comment by zachlatta** [comment]
I've created #379 to rename the folders to the new convention. Closing this in favor of that conclusion.
