### ISSUE TITLE
Is there anything we should do with this article

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#228]
Hell yeah @xeonjake!

See http://www.hackreactor.com/blog/san-leandro-high-school-launches-hack-club-with-hack-reactors-help

Should we cross-publish this anywhere?

/cc @xeonjake @zachlatta @hellyeah

**Comment by jonleung** [comment]
Should we post this in hackEDU leaderss?

**Comment by paked** [comment]
:+1:

**Comment by jonleung** [comment]
@gemmabusoni posted it! Thanks!
