### ISSUE TITLE
There are currently too many branches and it's confusing our club leaders

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#230]
Specifically @TheThirdOne and @Bogidon have brought up that our branch situation is not in a good condition. I agree with them. I think we should make an active effort to purge all branches that are not active. Thoughts @zachlatta @MaxWofford?

**Comment by paked** [comment]
:+1:

**Comment by MaxWofford** [comment]
:+1:

**Comment by Bogidon** [comment]
👍

**Comment by TheThirdOne** [comment]
:+1:

**Comment by TheThirdOne** [comment]
I would suggest for the future that everyone  contributing to a hackedu repo make feature branches in their own repo rather than hackedu's.

**Comment by Bogidon** [comment]
^ I agree with @TheThirdOne. When a club builds a new workshop they should do it in their own fork. After the workshop is built, they can submit it to hackedu through a PR. Maybe all the new workshops being added to the hackedu repo through PRs can go to a special branch (e.g. `workshop-testing`) if you still want to maintain some separation until the workshops are verified to work... but maybe the separation isn't needed.

**Comment by MaxWofford** [comment]
@Bogidon @TheThirdOne The current format for club leaders is to fork and submit a PR from their fork. Their pr commits are then cherry picked onto master. With this workflow, I don't think we'll have the need for a `testing` branch

**Comment by jonleung** [comment]
@MaxWofford, do you want to can take lead on removing as many unnecessary branches in our repo as possible?

**Comment by MaxWofford** [comment]
@jonleung The current precedent is for the submitter of the PR is to delete their branch after they are done with it. I would be happy to gently remind people about it, but I'm uncomfortable deleting other people's branches.

**Comment by TheThirdOne** [comment]
@MaxWofford That is why feature branches should only be in forks. Any branch then can only be deleted by its owner, but it doesn't clutter the main repo.

Any branches that have been merged into master should be safe to delete (after a list of branches to be deleted is posted in irc perhaps), and people should be messaged to move active branches to forked repos.

**Comment by TheThirdOne** [comment]
@paked, @jonleung, @saescapa, @MaxWofford, is there any specific reason yall created branches in this repo without cleaning up the branches in the past 6 days.

If you feel the need to keep a branch around to make revisions after its merged in, it should be in a fork.

Otherwise, please clean up your dead branches and be more careful in the future.

**Comment by Bogidon** [comment]
I haven't submitted a PR in over a week (I think). Right now I've gotten my fork in a bit of a muddle which is why I haven't submited any PRs. I think I'm going to clear the whole thing so I should be back to making PRs the right way in a few days.

**Comment by paked** [comment]
Whoops. I'll delete my outstanding branches now. Sorry @thethirdone.

**Comment by saescapa** [comment]
@TheThirdOne My 1 branch created 2 days ago has been deleted.

**Comment by MaxWofford** [comment]
@zachlatta Can we delete this now that the team is working from forks?

**Comment by TheThirdOne** [comment]
@MaxWofford 

There are 5 branches from the 25th. Until everyone actually follows through with it this should remain open.

Also a bunch of old branches (Early September) should be cleaned up before this is closed.

**Comment by MaxWofford** [comment]
@hackedu/core I'll set the deadline that any branches not deleted by the 5th of November will be removed.

**Comment by MaxWofford** [comment]
Assigning to myself to take point on this.

**Comment by saescapa** [comment]
@MaxWofford I'd be a good idea to retag everyone who has branches in hackedu.

**Comment by MaxWofford** [comment]
@saescapa Good point! ![](https://media2.giphy.com/media/k48soGtCrLqZq/giphy.gif)

cc/ @jonleung @zachlatta @hellyeah

**Comment by jonleung** [comment]
@MaxWofford should this still be in "this week"?

**Comment by MaxWofford** [comment]
@jonleung [yes](https://github.com/hackedu/hackedu/issues/230#issuecomment-152028365)

**Comment by jonleung** [comment]
:+1:

**Comment by jonleung** [comment]
@MaxWofford what if I don't want a branch to be deleted (i.e. I don't want my `curriculum-spiking` branch to be deleted)?

**Comment by zachlatta** [comment]
If you could fork the repo and make sure the forked `curriculum-spiking` branch is up to date, that'd be best.

**Comment by MaxWofford** [comment]
I'll be cleaning out the branches tonight!

**Comment by MaxWofford** [comment]
Closing because the only branches left are from PRs that will be closed soon
