### ISSUE TITLE
Do we want to set the precedent that every Lab Director will respond to GitHub mentions?

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#231]
This means that we need to set the precedent that Lab Directors will check GitHub notifications regularly.

I think that this will make it a lot easier to:

- get pull requests merged in (because discussion can happen much more quickly)
- allow Lab Directors to have discussions in comments on pull requests for case studies
- celebrate when people submit a pull request in the pull request itself

Thoughts @hellyeah @zachlatta @MaxWofford @xeonjake @paked @Bogidon?

**Comment by paked** [comment]
GitHub's notification UI does not make this task very easy IMO. What is the stance on using external software?

**Comment by Bogidon** [comment]
Recently I've been getting most GitHub notifications over email and they don't even show up at https://github.com/notifications (like the one for this issue). Other than having issues receiving the notifications, I like the GitHub issue/PR system and think it would benefit the Labs program to encourage it more.

**Comment by xeonjake** [comment]
Github on Android crashes alot for me, and also email doesn't always give me the full conversation. Any suggestions?

**Comment by paked** [comment]
Pinging @zachlatta because he mentioned he had a good workflow set out.

**Comment by zachlatta** [comment]
Yeah, so couple things about GitHub notifications:

- If you view a notification in your email, it's removed from the
notification center on GitHub's website
- If you view a notification in the web interface before they send you an
email notification (there's a tiny delay), they don't send the email
notification.

I personally manage my GitHub notifications from email and use a slightly
modified version of https://github.com/mastahyeti/OctoGAS to apply relevant
tags to notifications.

On Sun, Sep 20, 2015 at 2:28 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> Pinging @zachlatta <https://github.com/zachlatta> because he mentioned he
> had a good workflow set out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/231#issuecomment-141835885>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#300
