### ISSUE TITLE
Adding Lab Directors' GitHub handles to https://clubs.hackedu.us and the Labs Team

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#232]
I think we should gather all Lab Director's GitHub handle in https://clubs.hackedu.us. This will let us lookup people's GitHub handle from that spreadsheet when we want to ping them about something on GitHub (such as pull requests, discussions like this one, etc.)

Also, do we also want to add all the Lab Directors to the [Labs team](https://github.com/orgs/hackedu/teams/labs)? Right now it's just @gemmabusoni, @paked, and @zachlatta.

Thoughts @hellyeah @zachlatta @MaxWofford?

**Comment by zachlatta** [comment]
Yeah, I'm down with both collecting GitHubs and adding them to
@hackedu/labs. We currently have a "GitHub" column in the "Club Leaders"
sheet, we can put it there.

On Sat, Sep 19, 2015 at 7:26 PM, Jonathan Leung <notifications@github.com>
wrote:

> We can then lookup people's GitHub handle in https://clubs.hackedu.us
> when we want to ping someone about something.
>
> Do we also want to add all the Lab Directors to the Labs team
> <https://github.com/orgs/hackedu/teams/labs>? Right now it's just
> @gemmabusoni <https://github.com/gemmabusoni>, @paked
> <https://github.com/paked>, and @zachlatta <https://github.com/zachlatta>.
>
> Thoughts @hellyeah <https://github.com/hellyeah> @zachlatta
> <https://github.com/zachlatta> @MaxWofford <https://github.com/MaxWofford>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/232>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
Update:

I checked in with the Lab Directors this weekend to see if they were down for keeping updated on GitHub notifications. All of them said that they would be down. Many of them are familiar with how to check GitHub notifications. For those that are less familiar with checking GitHub notifications, I'm working with them closely to make sure that they are familiar with the flow and making sure that they're subscribed to email notifications (if that's what they want).

/cc @hellyeah @zachlatta @MaxWofford

**Comment by zachlatta** [comment]
They also should get emails with GitHub notifications.

On Mon, Sep 21, 2015 at 10:36 AM, Jonathan Leung <notifications@github.com>
wrote:

> Update:
>
> I checked in with the Lab Directors this weekend to see if they were down
> for keeping updated on GitHub notifications. All of them said that they
> would be down. Many of them are familiar with how to check GitHub
> notifications. For those that are less familiar with checking GitHub
> notifications, I'm working with them closely to make sure that they are
> familiar with the flow and making sure that they're subscribed to email
> notifications (if that's what they want).
>
> /cc @hellyeah <https://github.com/hellyeah> @zachlatta
> <https://github.com/zachlatta> @MaxWofford <https://github.com/MaxWofford>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/232#issuecomment-142052816>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
Closing this because it seems like no action will be taken.
