### ISSUE TITLE
Remote Control Workshop: The file sizes of the gifs are too large

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#241]
The file sizes of the gifs are currently too large. We may want to consider making them smaller.

/cc @TheThirdOne @zachlatta @ZucchiniZe

**Comment by TheThirdOne** [comment]
This also applies to the portfolio workshop.

**Comment by MaxWofford** [comment]
@TheThirdOne @zachlatta @ZucchiniZe
Git large file storage?

**Comment by TheThirdOne** [comment]
I think converting to mp4 then back to gif is probably the best choice. I might be able to improved the quality on the converted version.

Original (3.3 mb):
![original](https://raw.githubusercontent.com/hackedu/hackedu/9a9874787c66a0f052b79f5ab0a9de9225837e02/playbook/workshops/portfolio/img/img.gif)
Converted (700 kb):
![compressed](https://cloud.githubusercontent.com/assets/2322200/10009652/314c4b8c-6095-11e5-9931-38dd3344034b.gif)

**Comment by TheThirdOne** [comment]
Simply converting the gifs to gifs through cloudconvert.com provides 33% reduction in file size with perfect quality.

**Comment by ZucchiniZe** [comment]
@MaxWofford I don't think we should use Git LFS, since that adds another unnecesary step of complication which I think you guys are trying to keep to a minimum.

**Comment by MaxWofford** [comment]
@ZucchiniZe Just looked at Git LFS page, completely agree with you.

**Comment by TheThirdOne** [comment]
I made a simple script to convert using imagemagick. If this is is run on all current workshops (probably using rebasing) and all future workshops, this issue can be closed.

```
for f in *.gif; do
  mv "$f" "bak_$f";
  convert "bak_$f" "$f";
done
```

**Comment by TheThirdOne** [comment]
Why was #234 merged before this was fixed in it?

**Comment by MaxWofford** [comment]
@TheThirdOne This needs to be fixed. Cloning the hackedu/hackedu repo takes +5 minutes for me. Would you please run through and rebase the converted images and put them in a PR?

**Comment by MaxWofford** [comment]
@TheThirdOne Another version of the script:

```bash
for f in $(git ls-files | grep '/.gif$'); do
  mv "$f" "$f.bak";
  convert "$f.bak" "$f";
  rm "$f.bak";
done
```

**Comment by TheThirdOne** [comment]
@MaxWofford, have you tested that? I am not sure `convert` will be ok with a `.bak` file. Also if you don't need to keep the backup `convert "$f" "$f"` works fine.

**Comment by TheThirdOne** [comment]
@MaxWofford, I am fairly confident I don't have permissions to rebase. Do you mean make a commit after 74b607c to fix the images which you will rebase in?

**Comment by MaxWofford** [comment]
@TheThirdOne you can rebase a fork. @zachlatta would probably dislike changing history on master

**Comment by TheThirdOne** [comment]
@MaxWofford, how would rebasing a fork help?

**Comment by MaxWofford** [comment]
These images were scaled down.
