### ISSUE TITLE
workshop: Portfolio

### ISSUE THREAD

**Issue by saescapa** [hackedu/hackedu#247]
Moving signing up to the top to avoid loosing work and confusion with Github and JSBin. @jonleung

**Comment by saescapa** [comment]
@jonleung I can't assign myself :/.
I'll be working on it this week soon.

**Comment by jonleung** [comment]
Sounds good @saescapa!

**Comment by saescapa** [comment]
@jonleung Since I'm having PR conflicts, here is the file: https://github.com/saescapa/ap-comp-sci/blob/master/README.md

**Comment by zachlatta** [comment]
Closed by #455.
