### ISSUE TITLE
FizzBuzz workshop

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#25]
Put together a markdown lesson plan for the FizzBuzz workshop you're putting together. Would be great if you could resolve this with a PR.

**Comment by MaxWofford** [comment]
Hey, @Cydrobolt! Is this issue still relevant?

**Comment by Cydrobolt** [comment]
I think we can close this. I tried to do something like this in my club, it might have been a bit too simple to do as an activity with a lesson plan.

**Comment by MaxWofford** [comment]
@Cydrobolt Ok :-)
