### ISSUE TITLE
Check in with all club leaders meeting this week.

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#253]
@hellyeah, thoughts on taking this? We kinda discussed it a bit but I don't think we came to a conclusion.

**Comment by hellyeah** [comment]
Jumped on calls w/ Teagan, Tejas, and Jiahao. 

Need to make sure all notes get to clubs.hackedu.us

**Comment by zachlatta** [comment]
Status on this?

On Fri, Sep 25, 2015 at 9:13 AM, David Fontenot <notifications@github.com>
wrote:

> Jumped on calls w/ Teagan, Tejas, and Jiahao.
>
> Need to make sure all notes get to clubs.hackedu.us
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/253#issuecomment-143265325>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
Hopped on calls with Teagan, Tejas, and Jiahao. Jiahao ended up not having a meeting bc of change in their schedule. Tejas is now meeting every other week so they didn't have a meeting either.
