### ISSUE TITLE
Create script to quantify hackEDU Leaders Group Activity

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#258]

**Comment by paked** [comment]
This sounds fun. :+1:

**Comment by hellyeah** [comment]
I should probably clean up this code and also make the request work from the irc/slack bots, but this works now: https://github.com/hackedu/fb-group-stats

**Comment by hellyeah** [comment]
Next, I guess I should probably build this for Slack. Might want to try Go or something fun to be more clever, analyze the data on the fly, and not just store everything.

**Comment by paked** [comment]
@hellyeah this is dope. If you need any help with Go, I'd be happy to help :)

**Comment by jonleung** [comment]
@paked :+1:

**Comment by jonleung** [comment]
@hellyeah what are the next steps for closing this issue?

**Comment by hellyeah** [comment]
@jonleung I think this issue can likely be closed but a new one should be opened up to add the functionality to irc/slack bot. And maybe another issue for quantifying slack activity too.

**Comment by zachlatta** [comment]
Awesome, this looks good to go. I'll go ahead and create a new issue to track hooking this up with Steward.
