### ISSUE TITLE
Determine location for storing workshops

### ISSUE THREAD

**Issue by Bogidon** [hackedu/hackedu#262]
@zachlatta this relates to PR #245. In my PR I had the workshops Ajar.io & Cloud9 located in the `playbook/workshops` folder. I realize that the reason for not pulling them into that folder was because they were not tested. However this creates two problems:

- **limited visibility** - workshops are not easily found by others. The only way to see them (realistically) is if the person receives a link.
- **does not work for long-term workshops** - I want to continue my workshop over the course of several _weeks_. I can't currently do that with out 1) copying the workshop each time or 2) making changes to a workshop located in a previous meeting's folder :cry: 

I suggest creating a folder in `playbook/workshops` on `master` labeled "in review" or something similar. For now I will continue working on my Ajar tutorial in `case_studies/cherry_hill_high_school_east/15-09-21_c9_and_ajar.io_part_1`, but I don't think this is a sustainable model.

@jonleung @MaxWofford @TheThirdOne @paked @ssun098 thoughts?

**Comment by ssun098** [comment]
@Bogidon Perhaps we can have a separate workshops folder inside our individual case studies folder, so there's a centralised place where we can put them.  

@jonleung @MaxWofford @zachlatta thought?

**Comment by Bogidon** [comment]
@ssun098 that would solve the centralization issue. Visibility would be slightly better but still not great. Maybe there could be a table of contents at least for all the workshops. ¯\_(ツ)_/¯

**Comment by ssun098** [comment]
You could make a ToC in the README.md for that folder, if that would work?

**Comment by Bogidon** [comment]
That sounds like a pretty good approach. Curious to hear what others think.

**Comment by zachlatta** [comment]
How about we create a folder called `contrib` in `playbook/workshops`? That's a common folder name for contributions.

**Comment by ssun098** [comment]
@zachlatta I like the idea but how would you separate it out by school? Folder per school? It seems a bit hard to find your workshop is everyone else's workshop is there.

**Comment by zachlatta** [comment]
Collaboration! What if we didn't separate it by school? We could always
modify the file layout once it becomes a burden.

On Fri, Sep 25, 2015 at 9:28 PM, Selynna Sun <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> I like the idea but how would
> you separate it out by school? Folder per school? It seems a bit hard to
> find your workshop is everyone else's workshop is there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/262#issuecomment-143398372>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by ssun098** [comment]
:+1:

**Comment by ssun098** [comment]
I think that would be very effective, especially if leaders contributed to
each other's workshops, and improved theirs at the same time

**Comment by Bogidon** [comment]
Perfect. That was what I was trying to say in my original comment.

**Comment by paked** [comment]
This sounds great to me... However, have we thought about making workshops entirely different repositories? Just a thought. It would allow for less issue clutter on this repository, and a neater history all up.

**Comment by Bogidon** [comment]
@paked interesting. However if we separate workshops into a different repository `hackedu/hackedu` might develop some existential angst. It would then only be used for
1. case studies
2. internal labs stuff

Maybe the purpose of the `hackedu` repo can be clarified? Idk but for now I'll make that folder.

**Comment by paked** [comment]
@Bogidon The purpose could be to house the actual _playbook_. So things like the following:

* How to start a club
* Club organisation
* Running the club
* Day to day operations
* Contributing to workshops
* How to run workshops
* Running the club fair booth
* Recruitment

**Comment by Bogidon** [comment]
@paked yeah... the repo will need a facelift eventually then.

**Comment by MaxWofford** [comment]
Closing because @Bogidon fixed this in https://github.com/hackedu/hackedu/pull/283!

**Comment by zachlatta** [comment]
@paked I quite like the idea of eventually separating workshops into separate repos (perhaps we could use submodules or subtrees?). I'm partial towards keeping everything in this repo until things start to seriously break to keep the contribution barrier as low as possible (one repo is less to learn than many repos).

I'm going to go ahead and create a README in the `contrib` directory to better explain what it's for.

**Comment by paked** [comment]
:+1: for that

**Comment by zachlatta** [comment]
Just submitted #298 to describe what the `contrib` directory is for and assigned @paked to it.
