### ISSUE TITLE
How to cap lines at 80 characters in C9?

### ISSUE THREAD

**Issue by Bogidon** [hackedu/hackedu#263]
How do I cap the length of my markdown rows to 80 characters as required by the markdown conventions guide? Do I have to do this manually?

**Comment by MaxWofford** [comment]
@Bogidon Are you familiar with vim?

/cc @zachlatta

**Comment by Bogidon** [comment]
Hm true. I'm very basic at using Vim and need to get better. I'll probably use the Ace editor in C9 for now and break lines manually.

**Comment by MaxWofford** [comment]
@Bogidon Okay. If you ever do want to try vim, it's pretty quick to wrap at 80 chars. all you need to do to is:

1. `g g` jump to top of page
1. `shift+v` start selection buffer
1. `G` jump to bottom of page
1. `g q` word-wrap at 80 chars

**Comment by Bogidon** [comment]
Thanks @MaxWofford !

**Comment by paked** [comment]
@MaxWofford, should this be put somewhere formal?

**Comment by MaxWofford** [comment]
@paked Are the instructions clear for a beginner? I'd be happy to put them somewhere, but I'm hesitant to have everyone use this method.

**Comment by paked** [comment]
Mmm I agree. @Bogidon did you find a way to do this in the Ace editor?

**Comment by Bogidon** [comment]
There's a little character count indicator for each line. Using that for now.

**Comment by paked** [comment]
Ugh. There has to be a better solution

**Comment by paked** [comment]
[OK. I have tweeted at `@c9support`](https://twitter.com/hshoebridge/status/649134744261627904) because apparently that is a thing... Awaiting a reply!

**Comment by Bogidon** [comment]
good idea @paked! And good discovery about the twitter handle.

**Comment by paked** [comment]
This is the response I got: https://twitter.com/C9Support/status/649240109271924737

I guess we should convert it into text form somewhere @Bogidon 

cc: @zachlatta @jonleung @MaxWofford

**Comment by Bogidon** [comment]
Cool! Can you do that @paked? I could do it later probably

**Comment by paked** [comment]
I'll try and get around to it... If it isn't a PR in the next few hours you should take it.
