### ISSUE TITLE
Add missing clubs in the Airtable to https://clubs.hackedu.us

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#264]
Here is the [link to the Airtable](https://airtable.com/tblogRm7k8uC9ocU5/viw4nbNKwk4f1sIM0).

**Comment by zachlatta** [comment]
:thumbsup: :thumbsup: :thumbsup:

On Fri, Sep 25, 2015 at 9:04 AM, Jonathan Leung <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/264>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us
