### ISSUE TITLE
Improving community contribution via calls with leaders

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/hackedu#265]
Created by @gemmabusoni on @MaxWofford's computer
Call with Teagan

**Comment by paked** [comment]
Thoughts on a 24/7 hangout?

**Comment by zachlatta** [comment]
How'd this go? And @paked, do you mean something like https://partytime.hackedu.us?

**Comment by paked** [comment]
@zachlatta On some subreddits (namely [/r/gamedev](http://reddit.com/r/gamedev)) a hangouts is set up each weekend where anyone can drop by and work on their project surrounded by others, as well as ask for feedback and help from an engaged group of people. I'm not quite sure how this could logistically work within our community, but I believe it would drastically increase the bonds between individual members (IRC * 10).

**Comment by gemmabusoni** [comment]
How to do PR's, our guide specifically, doesn't seem to be very clear. Perhaps a call open to all clubs where pull requests and markdown are explained in detail?

**Comment by MaxWofford** [comment]
@gemmabusoni Some of this is because our PR workflow can be improved. We're having a discussion tomorrow at noon to look into alternatives.

**Comment by zachlatta** [comment]
Going to go ahead and close this because it's not clear how to proceed.
