### ISSUE TITLE
Page we can send people when they ask for the curriculum

### ISSUE THREAD

**Issue by paked** [hackedu/hackedu#268]
A common occurrence on IRC is for an outsider to pop by and ask:

> 00:00:00 – some_new_user – Where can I find the curriculum?

At the moment whoever is online at the time will usually reply with a link to http://github.com/hackedu/hackedu/blob/master/playbook/workshops... And then, upon realising that there is only one workshop begin linking to hackedu/hack-camp and various PRs lying around the place. It would be much more effective to have all these resources bundled together along with an explanation as to *why* it is arranged like this.

`ZucchiniZe` on IRC proposed setting up steward to have factoid support. However, I believe it should be ingrained in the actual repository.

> Factoid: an item of unreliable information that is reported and repeated so often that it becomes accepted as fact.

**Comment by paked** [comment]
cc: @hackedu/core

**Comment by MaxWofford** [comment]
@paked @hackedu/core: What do you think about adding a table of contents similar to https://github.com/syl20bnr/spacemacs/blob/master/README.md.

**Comment by MaxWofford** [comment]
Also, what if we flatten out the folder structure (ex. moving playbook/workshops/ to just workshops/)? It seems like we tried to future-proof the repo by adding a bunch of extra folders, but this may have just made it harder to navigate for our club leaders.

**Comment by paked** [comment]
Yeah. The current playbook folder seems a bit extraneous. I'd be down to move workshops to the top level.

Also, re: Navigating repository... #291

**Comment by paked** [comment]
Thoughts @zachlatta @jonleung @Bogidon ?

**Comment by Bogidon** [comment]
Agree with @paked that folder structure seems "extraneous". What are future plans for playbook @zachlatta @jonleung @MaxWofford?

**Comment by zachlatta** [comment]
Agreed as well. Let's move `playbook/workshops to just `workshops`.

**Comment by zachlatta** [comment]
Alright! I've submitted #377 that makes that change.

**Comment by MaxWofford** [comment]
@zachlatta Thanks!

Thoughts on adding a table of contents to the main README?

**Comment by paked** [comment]
Yes. 100% curriculum should be in the README.

**Comment by zachlatta** [comment]
@MaxWofford in #377 the README looks like this:

![tmp](https://cloud.githubusercontent.com/assets/992248/10629918/d266bc1a-7787-11e5-9c9d-a31f8b4ffaf6.png)

Do you want something in addition to that?

**Comment by MaxWofford** [comment]
@zachlatta Maybe we could make workshops more visible? 

Or we could add a table of contents similar to https://github.com/syl20bnr/spacemacs/blob/master/README.md.

**Comment by zachlatta** [comment]
Any suggestions for making it more visible? I'm open to having a table of contents, though I'm not sure what else we'd link to.

**Comment by MaxWofford** [comment]
I don't have any suggestions for increasing visibility right now :/
