### ISSUE TITLE
Ship 3rd Workshop to master: p5.js

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#271]
My plan is to write a workshop where you build a simple game like frogger with the p5.js and p5.play.js library.

[Here is some code I wrote](http://jsbin.com/yumape/9/edit?js) as a draft for what the final code might look like

In Part 1, you will build frogger by following a linear set of directions.
Part 2 will be buffet styles where I show you how you can add stuff like music, coins, and other things that you may want to add in your game and you can pick and choose what you want to add. Maybe you don't want to add any of the things that I've listed. Great, you can add something else not on the list.

**Comment by paked** [comment]
Woah p5 looks awesome!

**Comment by paked** [comment]
I was working on something kind of like this in #276

**Comment by jonleung** [comment]
Fixed by #323. @paked is currently helping me review and is submitting a new pull request to fix any issues he sees.

Thanks @paked!!!

**Comment by jonleung** [comment]
@paked made a pull request! I will be reviewing most likely tomorrow, possibly later tonight!

**Comment by paked** [comment]
:smile:
