### ISSUE TITLE
Club Leader Pairing

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#272]

**Comment by zachlatta** [comment]
As discussed, @gemmabusoni will be reaching out to @Bogidon to pair on `planning.md` and `recap.md`.

**Comment by gemmabusoni** [comment]
@jonleung mentioned that Bogdan is rather swamped this week. Haven't received feedback as to who I should potentially be partnering with instead.

**Comment by hellyeah** [comment]
Gemma and Jeremy (Lowell)

**Comment by gemmabusoni** [comment]
Call with Jeremy scheduled for 3pm Saturday. I'll be taking it from CalHacks, in case anyone else wanted to be involved.

**Comment by hellyeah** [comment]
@gemmabusoni how's this going?

**Comment by gemmabusoni** [comment]
@hellyeah Call was done on said day; he submitted to GitHub as well.

**Comment by MaxWofford** [comment]
@gemmabusoni Would you please link that here?

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#297
