### ISSUE TITLE
Finding clubs' recaps & feedback

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#277]
Many times I want to show the case study of one club to another club if they are going to run the same workshop. I want to be able to make the search query "show me the recaps that have done the portfolio workshop". I can't easily do that now and resort to opening ever club's case studies folder, then open every meeting folder, and then reading the recap to see if it covers the workshop or not...

Being able to see the feedback associated with a given workshop would also be incredibly helpful. How can we integrate this into packrat @zachlatta and @MaxWofford?

/cc @AbigailMed @amysorto @Bogidon @gemmabusoni @JevinSidhu @paked @sneharamapo @ssun @tejasmanohar @temucher @venethefifth @xeonjake @zachlatta @MaxWofford

**Comment by paked** [comment]
:+1:. This information should be available to club leaders too, on demand!

**Comment by MaxWofford** [comment]
@jonleung 
> Being able to see the feedback associated with a given workshop would also be incredibly helpful

Addressed in https://github.com/hackedu/hackedu/issues/338
