### ISSUE TITLE
Prepare for call with Ashley + Alt School Person

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#29]

**Comment by zachlatta** [comment]
Should this be in this repo?

**Comment by zachlatta** [comment]
Should this go into this repo?

**Comment by MaxWofford** [comment]
Moved from hack-camp/#70

- read q
- read thorough own notes
- Look through GWC
- funcs
- you have lots if project time
- testing knowledge 
- training how?
- idea of tutting everything
- lack of motivation in beginning
