### ISSUE TITLE
Twillio workshop README.md does not link properly

### ISSUE THREAD

**Issue by TheThirdOne** [hackedu/hackedu#290]
Github shows a 404 if you click any link.

This is because the links look like `[signup instructions for Twilio](/signup.md)` instead of `[signup instructions for Twilio](signup.md)`.

This is a easy fix, I can submit a PR.

@jonleung

**Comment by MaxWofford** [comment]
@TheThirdOne A PR for this would be great! If you start submitting one, just make sure to assign yourself this issue.

**Comment by zachlatta** [comment]
@MaxWofford we need to fix Markcop to catch this. Perhaps we should add some tests to Markcop?

**Comment by MaxWofford** [comment]
@zachlatta On mobile right now. Would you please add an issue for this?

**Comment by paked** [comment]
Fixed in #328
