### ISSUE TITLE
Workshop site

### ISSUE THREAD

**Issue by ZucchiniZe** [hackedu/hackedu#291]
Discussion for making a site that renders the workshops and easily allows people to comment on the content.

/cc @jonleung @TheThirdOne @ssun098

**Comment by TheThirdOne** [comment]
It might be possible to make this using Jekyll and github.

However, this will probably require a backend (possibly only for rendering). I would think it would be written in either Ruby, Python, Node, or maybe shell (using pandoc); I would be partial to shell or Node.

The commenting feature could use frontend JS using dweet (won't actually work because it is not permanent) or something similar. Or it could be hooked into pakrat as an api (/workshops/twilio/comments).

 @paked, talked about incorporating this into pakrat entirely.

**Comment by zachlatta** [comment]
What's the advantage to doing this now over using GitHub directly?

**Comment by TheThirdOne** [comment]
@zachlatta, It allows more flexibility (ex: using webm over gifs ), is potentially much better looking, and easier to find (workshops.hackedu.us).

**Comment by paked** [comment]
I wrote up a proposal for something along these lines at: hackedu/packrat#56

**Comment by paked** [comment]
OK. We just had the second "Curriculum Call". It was recognised that hackedu/packrat#56 that the technical debt would be too high to initially warrant building the initially proposed platform. Like all good engineers, we wrote up [some notes](https://beta.etherpad.org/p/curriculum-squad) and came up with a list of largest problems.

It was decided that we would like to continue with the idea, but focus on a smaller aspect of the solution: Viewing.

```
notes from the ethernote:

* Navigation is not great on GitHub when reading markdown
* Club members Viewing on GitHub has Distractions 
* Can't see other links to other workshops easily from GitHub 
* Can't go back without a short link (https://github.com/CHE-CS/hackedu/blob/ajar_5/playbook/workshops/contrib/ajar is hard to memorize)
* workshops.hackedu.us/(.*) would be much better
```

Not only is this a big pain point, but it actually has a not too complicated solution. [GitHub has a markdown rendering API](https://developer.github.com/v3/markdown/) which we could use.

Our revised MVP proposal is to create a [GitHub Pages](http://pages.github.com) branch on the hackedu/hackedu repository with the rendered markdown. For generating this, we have come up with two ideas:

1. Integrate the generation into the circle-ci build process. Setup [grip](https://github.com/joeyespo/grip) to render all the files using the `--export` feature.
2. Manually push the files generated with [grip](https://github.com/joeyespo/grip)

`Yeah, it pretty much is automated vs manual...`

If we choose to proceed we will need to rewrite the [workshops README](https://github.com/hackedu/hackedu/blob/master/playbook/workshops/README.md) file to be more student facing (It would be used as the landing page) and potentially move the workshops in [workshops/contrib](https://github.com/hackedu/hackedu/tree/master/playbook/workshops/contrib) up a level, for ease of access (http://workshops.hackedu.us/contrib/agar vs http://workshops.hackedu.us/agar).

Would love feedback.

cc: @zachlatta @ZucchiniZe @TheThirdOne @jonleung @Bogidon

**Comment by ZucchiniZe** [comment]
So, the markdown rendering API looks great, no more need for a backend.

I agree, some cli utility to render the markdown files to html sounds awesome and then putting them in the gh-pages branch with a automated ci buildstep sounds awesome, I would love to help to make the script/site.

**Comment by paked** [comment]
[I've written a basic bash script to compile all of the html](https://gist.github.com/paked/15833015ba1d6bb71b51)
```bash
for i in $(eval git ls-files | grep "\.md$");
do  
    printf "Compiling $i... ";
    grip --export --wide --pass <github_token_redacted> $i 2>/dev/null;
    printf "done\n";
done;
```

However, we have another few issues... Currently all the Markdown files link to other markdown files, as opposed to the HTML files.

Go has a really great and simple HTML AST package which could be used for the rewriting the URLs here. It'd work on the following rules:

- Any link to a `.md` file should be replaced with the `.html` equivalent
- Any link to a `README.md` should be replaced with a link to an `index.html`
- `README.md`'s should be rendered with the name `index.html`

I'm not going to go any further until we have a green light.

**Comment by TheThirdOne** [comment]
I would be hesitant to have the site hosted through gh-pages on hackedu/hackedu. I think it would be likely that it will be used for something else. Hosting using gh-pages on a separate repo like hackedu/workshops(-site)? would be better.

The site generator should be more complex than simply rendering the markdown (though that would be a great mvp). I would think a templating system (to wrap markdown pages with navigation and such), a gallery or workshops (automatically generated), and a few premade pages (homescreen).

I am very supportive of statically generating using circleci. 

@paked 

Great start with the script. I would think most of the features I mentioned could be easily implemented as bash scripts running after that initial step.

**Comment by paked** [comment]
@TheThirdOne hmmm. Any particular reason for not wanting it on hackedu/hackedu?

Of course @TheThirdOne. The current goal is to get it to an MVP stage, where we can tell if it could work. I don't actually think we would need a home page... The current `workshops` directory README would work initially.

Are you sure? Sounds like some regex magic too me... And you know what they say about HTML and regex!

**Comment by TheThirdOne** [comment]
@paked 

The repo is already plenty large as it is, something else may want to use hackedu/hackedu:gh-pages at some point, and just general separations of concerns.

I think the homepage is the least important of the features I mentioned. Markdown has a limit to prettyness though so I think in the long run having a custom html homepage would be nice.

I never mentioned regex. Templating would either use a framework or be made by prepending and appending the generated html.

That said I think regex is the best solution to the link rewriting. Something like /"(.*?)\.md"/"\1.html"/.

**Comment by paked** [comment]
@TheThirdOne Hmmm. Thoughts @zachlatta?

OK sure. But initially a markdown file is fine.

Are there bash HTML templating frameworks for this?

That regex looks fine to me.

**Comment by TheThirdOne** [comment]
Yeah, for MVP the markdown file is fine.

I was thinking `cat header.html file.html footer.html > file.tmp.html; mv file.tmp.html file.html` if we were using bash. Otherwise a non-bash templating framework would be better.

**Comment by jonleung** [comment]
@paked @zachlatta @TheThirdOne, thoughts on just using the `gh-pages` branch on `hackedu/hackedu` for now? When we decide to use the `gh-pages` branch for something else, I think then we could move this curriculum stuff somewhere else.

Moreover, I think it makes sense that if the curriculum lives in `hackedu/hackedu`, if we use a `gh-pages` branch, it should should live in the same repo. 

Moreover, I think it might make this process a lot easier if we didn't have to do things cross repo.

Thoughts @zachlatta?

**Comment by paked** [comment]
ping @zachlatta

**Comment by jonleung** [comment]
@zachlatta poke!

**Comment by MaxWofford** [comment]
Keeping gh-pages up to date with everything would be a  pain over time. The best option is putting our markdown on a website. We can probably set up a jekyll site that builds on filechange in hackedu/hackedu, but we have to fix our markdown first. Bad practices like quoted images should not be use in replacement of css fixes, and it would be prudent to fix everything while switching over (who knows how our markdown will end up rendering in jekyll).

**Comment by MaxWofford** [comment]
If we do want to do this with a `gh-pages` branch, we'll want add frontmatter to our markdown first: https://help.github.com/articles/using-jekyll-with-pages/#frontmatter-is-required

**Comment by ssun098** [comment]
@paked @jonleung 
![zachpoke](https://cloud.githubusercontent.com/assets/7741746/10620318/2ed3f958-772f-11e5-99f9-18d5de6f2650.png)

**Comment by MaxWofford** [comment]
That is amazing

**Comment by paked** [comment]
@ssun098 amen.

**Comment by MaxWofford** [comment]
Closing this because workshops are more accessible now: https://github.com/hackedu/hackedu/commit/f051fdafaeee248fbf87055f331bce944c74b557

**Comment by TheThirdOne** [comment]
@MaxWofford, linking the workshops in the README doesn't solve this. People have always been able to read the workshops on github; the workshop site is supposed to make that a better experience.

**Comment by MaxWofford** [comment]
@TheThirdOne Thanks for pointing that  out. I'm closing this issue because it is in the `new ideas` column, and no current discussion is happening.
