### ISSUE TITLE
Make it really easy to join our hackEDU channel

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#3]
Perhaps the channel is already open in the tab of our website where you can see all of the chat happening and you can just join in by typing your name

**Comment by MaxWofford** [comment]
There's a link to our channel on freenode in https://github.com/hackedu/hackedu/pull/67.

@zachlatta Could  get a code review and merge on this?

**Comment by zachlatta** [comment]
Yup! Looks good—just waiting on squash.

**Comment by zachlatta** [comment]
Closing because hackedu/hackedu#67 has been merged.
