### ISSUE TITLE
Add repository management guidelines into CONTRIBUTING.md

### ISSUE THREAD

**Issue by paked** [hackedu/hackedu#300]
@zachlatta tasked me with adding some contribution guidelines into the repository. He initially only specified the first item, although I believe the others should be considered.

1. Commits should be one logical unit of change
2. Commits should be written in the imperative mood, start with a capitol letter and not end with a full stop
3. Commits should explain the change, but not be longer than 50 chars

I understand that we aim to have a low barrier to entry, so perhaps it should be also stated that if your PR does not satisfy these requirements it will be be cherry picked.

cc: @MaxWofford @zachlatta

**Comment by MaxWofford** [comment]
:+1:

**Comment by paked** [comment]
This has been merged into master now with #366
