### ISSUE TITLE
Change Slack Settings

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#307]
* [ ] @everyone @channel @group @here admin only
* [x] display real first and last names by default
* [x] allow IRC gateways

**Comment by paked** [comment]
:+1:

**Comment by zachlatta** [comment]
IRC gateways are already enabled!

**Comment by paked** [comment]
@hellyeah I brought up the first point in slack. Wasn't able to get a discussion going though.

**Comment by hellyeah** [comment]
Looks like we're open to leaving @channel if it doesn't become a problem.
