### ISSUE TITLE
Schedule calls with the club leaders for each of our labs clubs

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#31]
As mentioned in our https://github.com/hackedu/hackedu/blob/71508adc8c092b2c1059cfa88b04537197a54635/meta/labs_program/meetings/15-07-13_initial_brainstorm.md discussion, before diving too deep into the specifics of each semester, we'll want to schedule a discussion with all of the club leaders from each of the clubs in our labs program to learn as much as possible about how their club functioned last semester

Reading through http://startupclass.samaltman.com/courses/lec16/ on doing user interviews may be helpful when talking with them.

This issue depends on #30.

/cc @jonleung

**Comment by MaxWofford** [comment]
Adding blocking tag because this is waiting for #30

**Comment by jonleung** [comment]
@zachlatta I think we should outline the specific workflow that we're using to get a club from on the spreadsheet to a call scheduled. I think having a clear deliverable will help the entire team reach it's goal. Would you like to create an issue / issues to outline that process?

**Comment by MaxWofford** [comment]
@jonleung Not sure if this is needed. I've already called 4/5 students just using the spreadsheet.

**Comment by zachlatta** [comment]
I'd be partial to just tracking this in the spreadsheet, as long as
everyone keeps it updated.

On Mon, Aug 17, 2015 at 5:21 PM, Max Wofford <notifications@github.com>
wrote:

> @jonleung <https://github.com/jonleung> Not sure if this is needed. I've
> already called 4/5 students just using the spreadsheet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/31#issuecomment-132003268>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@MaxWofford @zachlatta, perhaps we make an issue to make sure that the spreadsheet is updated and with what?

**Comment by zachlatta** [comment]
On Monday we changed the way we were going to do the labs program a bit. The original purpose of this interview, to find out what happened in clubs last year, will now be addressed during the interview process. I'm going to track progress on getting interviews set up in #54 instead.

**Comment by jonleung** [comment]
@zachlatta, @hellyeah, to my understanding, we are _**not**_ currently asking people how their club went last year are we? If we are not asking, I think we should.

**Comment by zachlatta** [comment]
Deferring to @hellyeah.

I know he has #65 open that outlines what's happening in calls.

**Comment by hellyeah** [comment]
I'll add this in. It ends up coming out implicitly almost every time bc I have them start me off with their story of entering HS but it should likely be more explicit.

**Comment by jonleung** [comment]
:+1:

**Comment by hellyeah** [comment]
Added this to #65 as question 0

**Comment by zachlatta** [comment]
:+1:

On Thu, Aug 20, 2015 at 10:04 AM, David Fontenot <notifications@github.com>
wrote:

> Added this to #65 <https://github.com/hackedu/hackedu/pull/65> as
> question 0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/31#issuecomment-133077527>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us
