### ISSUE TITLE
Add Slack IRC integration

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#310]
https://slack.zendesk.com/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP

https://ekmartin.com/2015/slack-irc/

Issues:
—you won’t be able to see who’s in irc and who’s in slack
—make it clear who’s first class users: 
—one channel called #irc where irc is first class users

**Comment by zachlatta** [comment]
Closing in favor of hackedu/meta#209.
