### ISSUE TITLE
Add slackin integration so we dont have to create @hackedu.us emails for club leaders

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#311]
http://rauchg.com/slackin/

**Comment by paked** [comment]
Are we still doing this? Or just inviting people manually

**Comment by ssun098** [comment]
Any updates? I think this would be really helpful for the club leaders community

**Comment by zachlatta** [comment]
And we're live! I've set up https://slack.hackedu.us.

_Source code: https://github.com/hackedu/slackin-off_
