### ISSUE TITLE
Set up Steward on Slack

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#312]

**Comment by hellyeah** [comment]
Think of a cuter, warmer name for Steward.

Make Steward welcome everyone who joins the Slack.

**Comment by zachlatta** [comment]
What if we just called Steward "Hubot"?

/cc @MaxWofford

**Comment by MaxWofford** [comment]
What if we called it `yo`. It's quick to type, and won't seem like a human.

**Comment by zachlatta** [comment]
I don't think there'll be too much confusion as to whether it's a human because Slack has a `bot` tag it puts next to its username and its profile picture is a robot.

Is your biggest complaint about calling it Hubot the length of the name?

**Comment by MaxWofford** [comment]
Also, nothing would be more amazing than this:
```
@msw: yo pug me
@yo(bot):
```
 ![](https://media.giphy.com/media/w7Y4xlQZG7qGA/giphy.gif)

**Comment by MaxWofford** [comment]
@zachlatta Mostly name length.

**Comment by zachlatta** [comment]
What about autocompletion? You should be able to type `hu<tab>` and have it autocomplete.

**Comment by MaxWofford** [comment]
@zachlatta I guess so.

**Comment by zachlatta** [comment]
Going to go ahead with Hubot for now. Also, @hellyeah, @ssun098 was saying that she didn't like how there was a bot that welcomed people and asked them to introduce themselves in the #hackers Slack.

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#278
