### ISSUE TITLE
credit card number in Twilio tutorial

### ISSUE THREAD

**Issue by ad510** [hackedu/hackedu#320]
Is the credit card number in the Twilio tutorial @jonleung's actual credit card number? If so, wouldn't that mean that people could charge to it?

I saw a couple people mention this on IRC on Monday but no one replied to it.

**Comment by zachlatta** [comment]
It's a prepaid card we bought at a store that doesn't have any cash on it, despite being a valid number. Would you be interested in submitting a pull request to clarify that?

**Comment by paked** [comment]
:+1: for adding that clarification note. Totally gave me a heart attack lol.

**Comment by paked** [comment]
I think we can close this now. @zachlatta clarified it was not a real credit card.
