### ISSUE TITLE
Create a Twilio proxy

### ISSUE THREAD

**Issue by bobacadodl** [hackedu/hackedu#322]
Unfortunately, my school's network seems to be blocking access to twilio.com (and maybe also twimlets.com ? never had time to check). Essentially, the script at bit.ly/twilio-basic-v1 fails when calling Twilio.callAndSay

We are currently working around this by using a mobile hotspot, and it works fine - but we would rather not use up data. If a proxy was setup so that we could access the APIs, it would be great!

**Comment by paked** [comment]
:+1:

**Comment by zachlatta** [comment]
Closed by #350. Thanks!
