### ISSUE TITLE
Dodge Workshop: alert("Game Over") => text(0,0, "Game Over"); player.remove();

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#325]
The alert was really annoying in the Dodge workshop.

Instead:

```js
text(0,0, "Game Over");
player.remove();
```

**Comment by paked** [comment]
After some inspection into this I don't think it is as simple as was initially thought by @jonleung.

The `text` function actually only renders the text for one frame. And currently, there is no way to check if a `sprite` is `dead` without setting an external variable. I am going to submit a PR/feature request to p5.play... In the meantime our `alert` solution will have to do.

**Comment by jonleung** [comment]
:+1:

**Comment by jonleung** [comment]
Wait @paked, what if we just removed the sprite instead?

**Comment by paked** [comment]
@jonleung that was the solution I settled for :)

**Comment by jonleung** [comment]
@paked could you link to your pull request you made for this here? Then feel free to close the issue!

**Comment by paked** [comment]
PR: #330
