### ISSUE TITLE
New members

### ISSUE THREAD

**Issue by j1lin0101** [hackedu/hackedu#333]
If new members were to come in and not understand the workshop have a reference, a short summary, or a link to the old lesson that explains it.

**Comment by paked** [comment]
@j1lin0101 our workshops are designed to not have linear order (at least so far), thus most people should be able to jump in and get started without a hitch. If this is a real problem that has popped up, would you mind telling us which workshop (and section) it was related to?

**Comment by j1lin0101** [comment]
Specifically the Twilio workshop. Some of new members came to my club last meeting while the rest of the group was working on the Twilio workshop and did not actually understand HTML and CSS. I eventually had to explain the concepts to them directly.

**Comment by paked** [comment]
@j1lin0101 that is interesting. @jonleung was the Twilio workshop designed be subsequent to the portfolio workshop? I know it has become almost tradition to run the Portfolio workshop as the first workshop, maybe that is why we haven't encountered this situation...

**Comment by zachlatta** [comment]
Oh, this is super interesting. What if we had "prerequisite concepts" or something listed, where "HTML & CSS" would be a prerequisite for the Twilio workshop and each prerequisite would have a link to a workshop that teaches the concept?

**Comment by jonleung** [comment]
@j1lin0101 @paked, I tried to make the Twilio Workshop not dependant on anything else. However, it does use 1 HTML tag. If the hacker had never written HTML before, they would have benefitted from doing the portfolio workshop before the Twilio workshop but I don't think by much. @j1lin0101, do you think it would have been very beneficial?

**Comment by j1lin0101** [comment]
@jonleung, I believe that if they know and understand what the tags are first then they would benefit greatly from it and easily understand where they are placing they're code and why

**Comment by paked** [comment]
@j1lin0101 What do we have to do we have to do to close this issue?

**Comment by j1lin0101** [comment]
@paked I would say on the future projects we should have short explanations or references that explain the topics mentioned.

**Comment by paked** [comment]
@bogidon lets get this into the workshop guidelines

**Comment by MaxWofford** [comment]
I like how `New members` is an issue

**Comment by Bogidon** [comment]
@paked let's do itttttttt!
