### ISSUE TITLE
Dodge Workshop is Currently Too Hard To Play

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#360]
Make the bullet slower. It's too hard to ~~win~~ stay alive right now.

**Comment by paked** [comment]
:+1:

**Comment by Bogidon** [comment]
Agreed

**Comment by jonleung** [comment]
@paked, I was wondering if you put this in the Todo column on Zenhub? Totally cool if you did! The expectation for many things in Todo though are that they are completed by the end of the sprint (Sunday night).

**Comment by paked** [comment]
@jonl yep. This looks like it was me (sorry).

**Comment by jonleung** [comment]
I just submitted a pull request for this fix. @paked, can you check to see if this version of the game is easy enough to play?
