### ISSUE TITLE
Let HackingEDU know which hackEDUers to expect to be at the hackathon

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#364]
@gemmabusoni @zachlatta, I pm-ed you a spreadsheet with the emails of hackEDU-ers who we are expecting to be at the HackingEDU Hackathon. This spreadsheet contains the hackers:

- name
- school
- email address they signed up with.

The task is to make sure that HackingEDU accepts all of them.

I'm not sure who is going to take lead on this task, @gemmabusoni or @zachlatta.

**Comment by gemmabusoni** [comment]
@jonleung I'll take lead. Will send to Keero asap.

**Comment by jonleung** [comment]
@gemmabusoni sounds good! I just assigned you to the issue!

**Comment by gemmabusoni** [comment]
Keero has all the spreadsheets and information. All we have to do now is ensure that all members print their respective waivers, have them signed, and take them to the event.

**Comment by jonleung** [comment]
Could you create an issue for making sure to communicate to club leaders that club members need to "print their respective waivers, have them signed, and take them to the event"? 

Also, I think there are probably club members on the spreadsheet that have not submitted applications. Could you do whatever it takes to make sure they can still go?  This could take the form anywhere from messaging club leaders to make sure that club members are registered to talking to Hacking EDU to make an exception for anyone who submitted a form to not have to submit an application.
