### ISSUE TITLE
Create a list of people that we are going to invite to the labs Program

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#37]
As discussed, @zachlatta will add the first 12 names of clubs that he already came up with.

@zachlatta should ping me after he adds this list.

Every applicant in this list needs to have an associated "code name" that is like a heroku server generated name.

See this letter for potential phrasing: https://gist.github.com/jonleung/f5760ba7876adb07fd35

**Comment by zachlatta** [comment]
Duplicate of #30.
