### ISSUE TITLE
Onboard all hackEDU leaders onto Slack

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#376]
**Especially**

- [ ] Cohort 2 Leaders
  - [ ] Add them to the `#cohort-2`
- [ ] Make sure everyone has accepted their slack invite (see https://hackedu.slack.com/admin/invites)
- [ ] Anyone else you think we should add

**Mobile App**
- [ ] Make sure everyone has
  - [ ] Downloaded the mobile app
  - [ ] Has enabled push notifications

@hellyeah @zachlatta, what are your thoughts on adding this task for this week?

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#237
