### ISSUE TITLE
Rename case study folders to new format and delete extraneous folders

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#379]
Rename the existing case study folders per the new format agreed upon in #227 and delete any empty folders that we created, since leaders will now be creating folders when needed.

**Comment by paked** [comment]
To quote the format...
> YY-MM-DD_meeting_title_{event|meeting}
>
> Examples:
>
> - `15-09-21_portfolio_workshop_meeting`
> - `15-09-15_club_fair_event`
> - `15-09-02_school_fundraiser_event`

**Comment by zachlatta** [comment]
Thanks @paked!

I think I'm actually going to change the folder format to have the full year because it'll be a bit clearer what that first number is. Ex. `2015-09-21_portfolio_workshop_meeting`.

**Comment by paked** [comment]
@zachlatta SGTM
