### ISSUE TITLE
Create title for Labs Program club organizer

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#40]
EDIT: 

For context, I think it could feel awesome to have an official title if you are in the labs program.

@zachlatta @MaxWofford @hellyeah

**Comment by MaxWofford** [comment]
Lab leader?

**Comment by jonleung** [comment]
@MaxWofford, eh not feeling `Lab leader`...

**Comment by jonleung** [comment]
@hellyeah any suggestions for this?

**Comment by zachlatta** [comment]
Going to discuss this as well during today's lunch.

**Comment by zachlatta** [comment]
Alright, we decided on "Lab Director". I created #60 to create a deliverable for this.
