### ISSUE TITLE
 Email Jonathan the progress update that you communicated to Sooz

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#41]
I am going to have a call with Sue's sometime this week and it would be good to be on the same page. It would be great if we can get this done end of day today.

EDIT BY @maxwofford: Changed to 1st person

**Comment by zachlatta** [comment]
You have it – I BCCed emails@hackedu.us on all my emails with her. Just
search for emails from me to her in your inbox.

On Wed, Aug 12, 2015 at 8:24 AM, Jonathan Leung <notifications@github.com>
wrote:

> Assigned #41 <https://github.com/hackedu/hackedu/issues/41> to @zachlatta
> <https://github.com/zachlatta>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/41#event-380434477>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Also, I think hackedu/meta may be a better place for issues like these in
the future.

On Wed, Aug 12, 2015 at 10:39 AM, Zach Latta <zach@hackedu.us> wrote:

> You have it – I BCCed emails@hackedu.us on all my emails with her. Just
> search for emails from me to her in your inbox.
>
> On Wed, Aug 12, 2015 at 8:24 AM, Jonathan Leung <notifications@github.com>
> wrote:
>
>> Assigned #41 <https://github.com/hackedu/hackedu/issues/41> to @zachlatta
>> <https://github.com/zachlatta>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackedu/hackedu/issues/41#event-380434477>.
>>
>
>
>
> --
> Zach Latta
> hackEDU | zach@hackedu.us
>



-- 
Zach Latta
hackEDU | zach@hackedu.us
