### ISSUE TITLE
Link to resources

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/hackedu#42]
There should be a link or directory to resources.

**Comment by zachlatta** [comment]
Resources?

-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
General hackEDU resources for organizers, sponsors, anyone interested in finding out more. Right now the only way for people to get info is to contact us through email. Maybe a link to github for now.

**Comment by MaxWofford** [comment]
Think this is validated by http://peek.usertesting.com/result/9829730887196?autoplay=true

What info does someone looking at our website want to get out of this?

**Comment by MaxWofford** [comment]
An example of this may be Taplytics accounts. How do our organizers know they have access to these resources?

**Comment by zachlatta** [comment]
Perhaps we can have a private repo that all of our club leaders have access to with access codes, that sort of thing.

**Comment by MaxWofford** [comment]
Closing this for the time being.

**Comment by zachlatta** [comment]
:+1:
