### ISSUE TITLE
Update apply date.

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/hackedu#43]
![apply](https://cloud.githubusercontent.com/assets/5891442/6154183/903d868a-b1de-11e4-873a-226e338ba410.png)

**Comment by MaxWofford** [comment]
Do we want to make this programmatically change to the next semester?

**Comment by zachlatta** [comment]
Might make the most sense to just say "accepting applications on a
rolling basis" or something along those lines.

-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
+1 this

**Comment by zachlatta** [comment]
Would you be interested in submitting a PR for this?

**Comment by MaxWofford** [comment]
resolved by PR#44
