### ISSUE TITLE
Schedule 4 paired calls with 8 club leaders

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#430]
@jonleung made tentative pairs here: https://docs.google.com/spreadsheets/d/1Mb-8WBjiZUOYgWqNJxaigCWZvZqnIHZ2ZhokVNCbJ4g/edit#gid=1880595778

**Comment by hellyeah** [comment]
Form for post-pairing call

**Comment by hellyeah** [comment]
We need to effectively track which leaders we've paired so we don't pair them too often.

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#263
