### ISSUE TITLE
Reach out to Abraham Lincoln high school

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#45]
We have decided to run clubs in SF. We already have a relationship with Abraham Lincoln high school so it will be easier to reach out to them to resume our club.

I would personally recommend co-leading the club with one of their students. 

EDIT by @maxwofford: I've removed the names

**Comment by MaxWofford** [comment]
@jonleung I've removed the full names of individuals at this high school for privacy reasons.

**Comment by MaxWofford** [comment]
@jonleung Closing this issue because it is covered in https://github.com/hackedu/hackedu/issues/47
