### ISSUE TITLE
Plan and Schedule future curriculum calls

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#456]
I've dropped the ball on making this happen. Let's set this up again.

Before each call, we should have a clear objective of what we want to get out of the call.
More concretely, each call should also have an agenda.

\cc @Bogidon @paked @JevinSidhu

**Comment by zachlatta** [comment]
Can you clarify what you mean by a "curriculum call"?

**Comment by jonleung** [comment]
Calls where we talk about curriculum in general, how to collaborate on it, what we might change, what's working and not working, etc.

**Comment by zachlatta** [comment]
Could these be done during the pairing calls?

**Comment by paked** [comment]
@zachlatta It has worked really well having a group of people come together to talk about *one* specific topic.

**Comment by zachlatta** [comment]
Ah, gotcha. Proceed as planned that.

**Comment by paked** [comment]
I'd love to be kept in the loop about this. I can do Fridays and Saturdays 3pm onwards (Thanks Australia!), although understand that that makes it difficult for everyone.

**Comment by jonleung** [comment]
Fridays work best for me right now.

**Comment by jonleung** [comment]
@JevinSidhu  Friday doesn't work for you though?

**Comment by JevinSidhu** [comment]
@jonleung They are harder for me, but I can make something work! 

@paked Saturdays from 3pm PT works for me :)

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#303
