### ISSUE TITLE
Weekly Call, Do We Want It

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#457]
Now that we've merged labs and are also doing pairing, @hellyeah, we should think about what the weekly call will look like. Do we still want them? If so, how might that work?

**Comment by zachlatta** [comment]
When did we merge the Labs cohorts?

**Comment by jonleung** [comment]
Just now.

**Comment by MaxWofford** [comment]
@jonleung Should this have a `discussion` label?

**Comment by zachlatta** [comment]
Thoughts on planning to have a weekly call?

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#304
