### ISSUE TITLE
Going to slack.hackedu.us should redirect to hackedu.slack.com if I already have an account

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#461]
Right now when I go to `slack.hackedu.us` it just sits on the page.

![image](https://cloud.githubusercontent.com/assets/654941/10924693/5afac318-823d-11e5-8a7d-29747e813933.png)

It should instead redirect me to `hackedu.slack.com`

I know that @hellyeah knows a way to do this.

/cc @zachlatta

**Comment by jonleung** [comment]
Moreover, if I I try to type in my email and I already have an account, it should redirect me to `hackedu.slack.com` as well and not do this:

![](https://s3.amazonaws.com/f.cl.ly/items/2l0Z031Q0x3V3G0t3o1o/Screen%20Recording%202015-11-03%20at%2003.15%20PM.gif)

**Comment by zachlatta** [comment]
@hellyeah Where have you seen this done before?

**Comment by MaxWofford** [comment]
@jonleung How will you type in your email if you've been redirected?

**Comment by zachlatta** [comment]
This issue was moved to hackedu/meta#306
