### ISSUE TITLE
Create task list for prepping for first club meetings

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/hackedu#47]
Moved from https://github.com/hackedu/hack-camp/issues/500

Create bullet-point list of what needs to happen from now until first meeting for the following:

- @saescapa
- @xeonjake 
- Lowell's club
- @amysorto 

Put notes from each call (containing bullet points) in https://github.com/hackedu/hackedu/tree/master/meta/labs_program/meetings.
Track progress of this task (like saying when a call with one of the people is happening) by commenting on this issue.

**Comment by MaxWofford** [comment]
@jonleung Has volunteered to take point on reaching out to @amysorto and Lowell's club.

**Comment by MaxWofford** [comment]
I don't think this issue is relevant. Each of the clubs we listed may become Labs, in which case we'll be working with them through this list anyways. It would be better to handle everything in one batch. Thoughts @jonleung?

**Comment by MaxWofford** [comment]
@jonleung What is this blocking on?

**Comment by jonleung** [comment]
@MaxWofford I accidently added the `blocking` tag. I just removed it from this issue.

**Comment by jonleung** [comment]
In our current schedule, Lab Directors sign their contracts by Friday, August 28th. ([Here is a link](https://gist.github.com/zachlatta/a50609d72e96957d6b04) to the deadlines for the Labs program)

This means we won't have Lab Directors to talk to before August 28th.

Our entire team is also gone starting on the 30th of August. This means that we won't actually be able to chat with Lab Directors until our team gets back on September 8th.

By this point, we will have missed too many things at the beginning of the club lifecycle.

For example, Lowell High School had their club fair on August 10th.

It is important for us to capture what these events are and how to effectively them in our playbook. It seems like the only way to capture these events is to talk to club leaders who are not officially part of the Labs Program yet.

@amysorto seems very busy this week. I may postpone on talking to her until next week. I may find some other club leaders to talk to this week.

**Comment by MaxWofford** [comment]
@jonleung Not sure I understood:
> It is important for us to capture what these events are and how to effectively them in our playbook

**Comment by jonleung** [comment]
@MaxWofford, let me try to rephrase:

There's stuff that happens for a club between August 19th and September 8th. I want to know what those things are and document how to do them in the club playbook. The only way to do that is to interface with club leaders before they are officially Labs club leaders.

**Comment by jonleung** [comment]
@MaxWofford, are you reaching out to @saescapa and @xeonjake?

**Comment by jonleung** [comment]
Just an update, I've decided not to reach out to @amysorto for now because she seems to be extremely busy! Enjoy the rest of your summer @amysorto before school starts!

**Comment by zachlatta** [comment]
@jonleung can you submit a pull request with what you know needs to happen for Lowell?

**Comment by jonleung** [comment]
@zachlatta, yes! I will submit a pull request by the end of the day today.

**Comment by jonleung** [comment]
@MaxWofford, is it ok if I just link [my personal notes](https://gist.github.com/jonleung/a287d2f8b20134f11ce2) in this issue here? It is not the most human readable, but I think it is good enough for now.

**Comment by MaxWofford** [comment]
I'm confused what that question is for. You just linked your person notes.

**Comment by zachlatta** [comment]
I'm with @MaxWofford on this one.

On Mon, Aug 24, 2015 at 12:45 AM, Max Wofford <notifications@github.com>
wrote:

> I'm confused what that question is for. You just linked your person notes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/47#issuecomment-134076289>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta and @MaxWofford, the objective of this task is to make sure that we know everything that needs to be done up until the first club meeting. If I finish https://github.com/hackedu/hackedu/issues/87, I will have met the aforementioned objective. Therefore I am closing this task.
