### ISSUE TITLE
Send out contracts and rejections

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/hackedu#48]
Send out all contracts and rejections by Tuesday (08/25)

**Comment by MaxWofford** [comment]
This is blocking on #39 & #31.

**Comment by hellyeah** [comment]
I'll be sending acceptance emails to people after Zach calls them. 

He's italicizing the names of club leaders in the spreadsheet that he's jumped on a call with so that I know which leaders to email.

**Comment by hellyeah** [comment]
acceptance email (draft): https://gist.github.com/hellyeah/60b5322e9ec9f054f341

rejection email (draft): https://gist.github.com/hellyeah/d397f84d0e42e6472982

**Comment by zachlatta** [comment]
All acceptances for the first cohort called and emailed.

**Comment by zachlatta** [comment]
Let's wait on sending out rejections until tomorrow (Thursday), so we can make sure everyone we invited accepts first.

**Comment by zachlatta** [comment]
To clarify, I'll be sending the acceptance and rejection emails.

**Comment by zachlatta** [comment]
I opened #98 to add the acceptance email I sent the first cohort.

**Comment by hellyeah** [comment]
Awesome. Cohort 1 and Cohort 2 Labs Directors have been accepted. 

See #94 #83 

Awaiting responses.

**Comment by hellyeah** [comment]
New draft: https://gist.github.com/hellyeah/d397f84d0e42e6472982

**Comment by hellyeah** [comment]
I sent rejection emails.
