### ISSUE TITLE
Create bullet point outline of what to cover in labs interview calls

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#49]

**Comment by MaxWofford** [comment]
@hellyeah What does this issue entail?

**Comment by MaxWofford** [comment]
What is the deliverable for this issue? (When do we close this issue?)

**Comment by jonleung** [comment]
bullet points of everything we need to mention in call -@hellyeah

**Comment by MaxWofford** [comment]
@hellyeah, I noticed your comment:
>bullet points of everything we need to mention in call
is different than the title of the issue:
`Talk to every labs director about gender diversity in labs club leadership`.
So I'm on the same page. What do we have to do to close this issue?

**Comment by zachlatta** [comment]
@MaxWofford I believe @jonleung's comment was to mention the deliverable for the task.

So, to my understanding, the deliverable is a markdown file with bullet points of everything needed to be mentioned in the call. One of those bullet points would be mentioning gender diversity.

**Comment by MaxWofford** [comment]
What if we changed the title of the issue to the deliverable?

**Comment by hellyeah** [comment]
Bullet points to cover in labs interviews (feel free to append): https://gist.github.com/hellyeah/6ab8c870348804d10e3f

**Comment by zachlatta** [comment]
I pinged you on IRC asking you to submit a PR for this :-).

On Wed, Aug 19, 2015 at 11:11 AM, David Fontenot <notifications@github.com>
wrote:

> Bullet points to cover in labs interviews (feel free to append):
> https://gist.github.com/hellyeah/6ab8c870348804d10e3f
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/49#issuecomment-132726568>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
How do I get the PR to automagically show up here?

**Comment by zachlatta** [comment]
If you mention this issue's number (`#49`) in the description of the PR, it gets automatically linked.

**Comment by hellyeah** [comment]
So whats the point of mentioning it in the commit if youre going to mention it in the PR also?

**Comment by jonleung** [comment]
@zachlatta, your thoughts may be useful here.

**Comment by zachlatta** [comment]
Thanks @jonleung!

If you say something along the lines of "closes #134" in the commit message, when the commit is merged to master #134 will be closed automatically. See https://help.github.com/articles/closing-issues-via-commit-messages/.

The duplication is a bit annoying.

**Comment by hellyeah** [comment]
What's stopping us from closing this issue?

**Comment by zachlatta** [comment]
I left a couple comments in #65 that I'm waiting on you to get back to :-).

On Thu, Aug 20, 2015 at 6:58 PM, David Fontenot <notifications@github.com>
wrote:

> What's stopping us from closing this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/49#issuecomment-133245439>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
Awesome. Just added the lines before lists. Now I have to figure out how to get this rebase working. I may need your help bc it seems like I did something wrong.

**Comment by zachlatta** [comment]
@hellyeah feel free to grab me in person or ping me on IRC for this.

On Fri, Aug 21, 2015 at 2:28 PM, David Fontenot <notifications@github.com>
wrote:

> Awesome. Just added the lines before lists. Now I have to figure out how
> to get this rebase working. I may need your help bc it seems like I did
> something wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/49#issuecomment-133567643>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
See #77
