### ISSUE TITLE
Introduce all club leaders to Dave for interviews

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#54]
Spreadsheet linked in https://github.com/hackedu/hackedu/tree/master/meta/labs_program.

/cc @jonleung @hellyeah

**Comment by zachlatta** [comment]
Messaged all the people in the sheet assigned to me, waiting on their responses...

**Comment by zachlatta** [comment]
Time to message a couple more people!

**Comment by hellyeah** [comment]
I need to update this spreadsheet: https://docs.google.com/spreadsheets/d/1Q6E36NK7N_mKp_LJwMW-P3KUZXPsHQTJWyoyKvrneuc/edit#gid=0

**Comment by zachlatta** [comment]
@jonleung is there anyone else you want to add to the spreadsheet?

**Comment by zachlatta** [comment]
@jonleung can you make sure the club on row 22 gets in our pipeline?

**Comment by jonleung** [comment]
@zachlatta 

> @jonleung is there anyone else you want to add to the spreadsheet?

Yes. I am currently working to add more female club organizers to the spreadsheet.

> @jonleung can you make sure the club on row 22 gets in our pipeline?

Yes, I will make sure to take care of it.

/cc @hellyeah

**Comment by zachlatta** [comment]
Went ahead and removed the blocking tag for now, since people I'm messaging respond in variable intervals.

I've introduced everyone except for two. Just waiting on their responses.

**Comment by zachlatta** [comment]
Alright, still waiting on their responses. I move for us to move forward with this. I'll submit a PR for moving forward.

**Comment by zachlatta** [comment]
Alright, PR submitted. #75.
