### ISSUE TITLE
Get all contracts signed

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#55]

**Comment by hellyeah** [comment]
Where are we keeping track of contracts being signed?

**Comment by zachlatta** [comment]
I think we can actually probably close this issue outright, since we're not
sending them contracts. They're just confirming over email.

On Wed, Aug 26, 2015 at 1:01 PM, David Fontenot <notifications@github.com>
wrote:

> Where are we keeping track of contracts being signed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/55#issuecomment-135155158>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Going to go ahead and do that. Let me know if anyone thinks we should
reopen it!

On Thu, Aug 27, 2015 at 9:36 AM, Zach Latta <zach@hackedu.us> wrote:

> I think we can actually probably close this issue outright, since we're
> not sending them contracts. They're just confirming over email.
>
> On Wed, Aug 26, 2015 at 1:01 PM, David Fontenot <notifications@github.com>
> wrote:
>
>> Where are we keeping track of contracts being signed?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackedu/hackedu/issues/55#issuecomment-135155158>.
>>
>
>
>
> --
> Zach Latta
> hackEDU | zach@hackedu.us
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
Closing this issue because it seems like it should be closed.

**Comment by zachlatta** [comment]
Good catch, I had forgotten to close it. My bad!

On Fri, Aug 28, 2015 at 11:41 AM, Jonathan Leung <notifications@github.com>
wrote:

> Closing this issue because it seems like it should be closed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/55#issuecomment-135857021>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us
