### ISSUE TITLE
Typo missing 'by'

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#57]
Typo: At the top two collegiate hackathons in the world, PennApps X and MHacks V, half of the six winning teams were led *by* high school students.

**Comment by zachlatta** [comment]
Can you submit a PR for this?

**Comment by MaxWofford** [comment]
Fixed [here](https://github.com/hackedu/hackedu/commit/6a3064f0c3c192936f990dac3cf0356c639e2376)
