### ISSUE TITLE
Build an autonomous community for non-labs clubs.

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#58]

**Comment by MaxWofford** [comment]
@hellyeah This seems like a very large issue that incorporates many smaller tasks. Do we know those other tasks? 
If so, let's break it up into those smaller tasks.
If not, perhaps the actionable issue here is to schedule a planning meeting to figure out those tasks.

**Comment by hellyeah** [comment]
Scheduled a lunch meeting for tomorrow at noon with @zachlatta and @jonleung 

@MaxWofford I think you're right. This leads directly to the broader question of what we want the hackEDU community to look like.

**Comment by hellyeah** [comment]
Submitting this as a PR shortly: https://gist.github.com/hellyeah/cf744f491cff2c88c2ff

**Comment by zachlatta** [comment]
Has it been submitted as a PR?

On Fri, Aug 28, 2015 at 3:54 PM, David Fontenot <notifications@github.com>
wrote:

> Submitting this as a PR shortly:
> https://gist.github.com/hellyeah/cf744f491cff2c88c2ff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/58#issuecomment-135906015>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
None of the leaders we emailed to post in the Facebook Group did so. 

I need to revisit our messaging there.

**Comment by zachlatta** [comment]
Has it been pretty effective when messaging people individually to post? If
so, perhaps we should just do that moving forward.

On Mon, Aug 31, 2015 at 11:28 AM, David Fontenot <notifications@github.com>
wrote:

> None of the leaders we emailed to post in the Facebook Group did so.
>
> I need to revisit our messaging there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/58#issuecomment-136454567>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
^ @hellyeah

**Comment by hellyeah** [comment]
Messaging people individually to post worked effectively.

This PR should be ready for review+merge: #137

**Comment by jonleung** [comment]
Merged!
