### ISSUE TITLE
Create Medium Publication for hackEDU

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#59]

**Comment by MaxWofford** [comment]
@hellyeah What does this issue title mean?

**Comment by hellyeah** [comment]
https://medium.com/hack-edu

**Comment by zachlatta** [comment]
Any chance we could get https://medium.com/hackedu?

One more quick thing: we generally stylize our name as hackEDU (even when
at the beginning of sentences). This isn't clear anywhere though – I'll add
an issue to make sure that we outline how we stylize our name somewhere.

On Wed, Aug 19, 2015 at 11:45 AM, David Fontenot <notifications@github.com>
wrote:

> https://medium.com/hack-edu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/59#issuecomment-132738667>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
I tried hackEDU first but it doesn't satisfy their naming guidelines: https://www.dropbox.com/s/vnyv2cyd9q2atn6/Screenshot%202015-08-19%2011.59.35.png

**Comment by hellyeah** [comment]
Open to a name change.

**Comment by MaxWofford** [comment]
@hellyeah If you drag files onto the comment box with ZenHub running, it will automatically upload them to imgur and add a link.

**Comment by hellyeah** [comment]
Are there any decisions left to be made here? If not, can we close the issue?

**Comment by zachlatta** [comment]
I'd like to find a title for the publication that'd work well. Thoughts on
"hackEDU Hackers"? I'm not a very big fan of it, but I figure it's better
than nothing.

On Thu, Aug 20, 2015 at 6:59 PM, David Fontenot <notifications@github.com>
wrote:

> Are there any decisions left to be made here? If not, can we close the
> issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/59#issuecomment-133245548>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
I think hackEDU looks really strange in the title but I'm open to it.

https://photos-4.dropbox.com/t/2/AAA8Kxk_k9KwxYJV3OrcfVHhuIYvLqq_cb42-4WC6x-0Ow/12/68038202/png/32x32/1/1440212400/0/2/Screenshot%202015-08-21%2018.35.19.png/CLrcuCAgASACIAMgBCAFIAYgBygCKAc/TIXimNQhTUWxTsAL7BtXqHp8WHE3Vyby7UL4ayyUGYg?size=800x600&size_mode=2

**Comment by hellyeah** [comment]
I think the hackEDU blog could be the definitive blog for running HS clubs though and that we could take a more general title that lets us own more content. 

I imagine even non-coding clubs submitting posts to the publication about how they successfully ran their HS clubs. Let me know what you think.

**Comment by hellyeah** [comment]
I just worry that "hackEDU Hackers" is restrictive and makes it seem like the content is only for people within the community who already know what hackEDU is whereas the point of the blog could be primarily to reach people outside of our community.

**Comment by MaxWofford** [comment]
@hellyeah: I agree that it seems exclusive to just hack clubs. Also, *hack*EDU *Hack*ers seems kinda repetitive. Any ideas what we want to call the hackEDU blog to make it more inclusive?

**Comment by zachlatta** [comment]
Yeah, I'm also on board with calling it something without "hackEDU" in the
name. Let's try to move on this ASAP.

Any ideas @hellyeah? We also also schedule a quick call between us to hash
out a new name sometime today.

On Mon, Aug 24, 2015 at 1:31 AM, Max Wofford <notifications@github.com>
wrote:

> @hellyeah <https://github.com/hellyeah>: I agree that it seems exclusive
> to just hack clubs. Also, *hack*EDU *Hack*ers seems kinda repetitive. Any
> ideas what we want to call the hackEDU blog to make it more inclusive?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/59#issuecomment-134093381>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
https://photos-1.dropbox.com/t/2/AACUHmhQYvApc5prQYzPUXXfDV3DEXSLNw0w1qa_zcpnAQ/12/68038202/png/32x32/1/1440525600/0/2/Screenshot%202015-08-25%2009.47.53.png/CLrcuCAgASACIAMgBCAFIAYgBygCKAc/W1fKUFHbna66wCpFgVDqNhTKJeLKM1fZ47dUzorsI3E?size=800x600&size_mode=2

**Comment by hellyeah** [comment]
I also Facebook messaged the person who owns medium.com/hack-education

**Comment by zachlatta** [comment]
Hmm, I'm not the biggest fan of "Hack Education" because I'm worried that people will assume that hackEDU is short for Hack Education if they see the blog.

Perhaps we could set aside 15 minutes to chat synchronously as a team today, like we did when trying to come up with the Lab Director title?

**Comment by hellyeah** [comment]
Going to set up a meeting to discuss
Medium Publication: #59
Non-labs club: #52
Community:  #58

**Comment by hellyeah** [comment]
Punted this specific issue from the previously mentioned meeting. Setting up a meeting tomorrow to discuss this specifically. May be blocking on "Hack Club."

**Comment by zachlatta** [comment]
Sounds good! Looking forward to discussion tomorrow.

On Thu, Aug 27, 2015 at 3:20 PM, David Fontenot <notifications@github.com>
wrote:

> Punted this specific issue from the previously mentioned meeting. Setting
> up a meeting tomorrow to discuss this specifically. May be blocking on
> "Hack Club."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/59#issuecomment-135572271>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
@hellyeah can you add the conclusion from the meeting we had this morning about what to name the publication?

**Comment by hellyeah** [comment]
Title: "Hack Club"
Description: "The worldwide movement of student-led hacker communities"

<img width="1223" alt="screenshot 2015-08-28 15 21 36" src="https://cloud.githubusercontent.com/assets/1475361/9558278/8860c3d6-4d98-11e5-85a0-efa91af7636b.png">

**Comment by zachlatta** [comment]
:+1:

On Fri, Aug 28, 2015 at 3:22 PM, David Fontenot <notifications@github.com>
wrote:

> Closed #59 <https://github.com/hackedu/hackedu/issues/59>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/59#event-395534378>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
Stories of Hack Clubs across the country.
Stories from club leaders to start a computer programming clubs.
Stories
Stories from Hack Clubs across the country.
Stories about creating what you see missing in the world.
Slice of life from programming clubs across.
Creating communities worldwide.
Hack Club editorials
Cross-sections of Hack Clubs
Creating coding communities worldwide.
The student-led movement of coding communities
The student-led movement of hacker communities


Creating the future of programming clubs across the country.
Laying the foundation of programming clubs across the country.
Hacking

Top HS club leaders share their stories

The student-led hacking movement

**Comment by zachlatta** [comment]
Hmm?

On Mon, Aug 31, 2015 at 5:35 PM, David Fontenot <notifications@github.com>
wrote:

> Stories of Hack Clubs across the country.
> Stories from club leaders to start a computer programming clubs.
> Stories
> Stories from Hack Clubs across the country.
> Stories about creating what you see missing in the world.
> Slice of life from programming clubs across.
> Creating communities worldwide.
> Hack Club editorials
> Cross-sections of Hack Clubs
> Creating coding communities worldwide.
> The student-led movement of coding communities
> The student-led movement of hacker communities
>
> Creating the future of programming clubs across the country.
> Laying the foundation of programming clubs across the country.
> Hacking
>
> Top HS club leaders share their stories
>
> The student-led hacking movement
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/59#issuecomment-136537380>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us
