### ISSUE TITLE
Write follow up email for Labs interviews

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#62]

**Comment by zachlatta** [comment]
:thumbsup:

Can you submit a PR to close this, when you do it?

On Wed, Aug 19, 2015 at 10:10 AM, David Fontenot <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/62>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
Yes. I'll write the email after my next interview, turn it into a template, and submit a PR.

**Comment by zachlatta** [comment]
Awesome! Sounds good.

On Wed, Aug 19, 2015 at 12:43 PM, David Fontenot <notifications@github.com>
wrote:

> Yes. I'll write the email after my next interview, turn it into a
> template, and submit a PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/62#issuecomment-132755604>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
When I was in high school, my entire world was just the beach in Hollywood,
Florida -- I didn't do shit. Talking to you about the community you're
building at your high school left me feeling inspired for the future of the
world.

As a student who's running a coding club at your high school, you are
paving the way for thousands of students around the world who will start
coding clubs after you. You're setting the new status quo for what people
can expect from high schoolers.

We are going to work day and night to have a decision to you by end of day
Wednesday.

Regardless of whether you become a Labs Director, we want to showcase your
club to the world. If you write a "Hello, World!" draft for your club,
share it with us so we can add it to our new hackEDU Medium publication:
https://medium.com/hack-edu/latest

Also, we love feedback! Have any ideas for hackEDU labs or even just a
better title/description for our Medium publication? Just reply to this
email.

-Dave

**Comment by MaxWofford** [comment]
@hellyeah What is a `"Hello, World!" draft for your club`?

**Comment by hellyeah** [comment]
It's something I encouraged club leaders to write after our interview calls. 

It's a blog post that says "Hello, World! Our club exists."

**Comment by hellyeah** [comment]
Sent this to everyone I interviewed last week. Can we close this issue?

**Comment by zachlatta** [comment]
Can you submit a PR with it so we have it in the repo?

**Comment by hellyeah** [comment]
See #81
