### ISSUE TITLE
Write script for call to tell club leaders they are chosen for the labs program

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#69]
As discussed by @hellyeah and I in the `hackedu` IRC channel on August 20th at around 6:40pm:

- We will select all Lab Directors by Tuesday the 25th
- We will call them all by Wednesday the 26th

The task at hand is to put together a call script. As discussed, it will look something like this:

> Congrats! You have been selected...
> Know that this is a really big time commitment
> We expect at minimum, 5 hours per week
> Do not take this lightly
> It's totally fine to turn this down. We understand that you're busy.
> Talk it through with your team.
> If you decide that guys are up to the challenge, let us know.
> If you cannot, that's totally cool too.
> Let us know either way by responding to our email by Friday at 8pm PST.
> If you are choosing to be a Lab Director, please respond to the email with the signed contract.

/cc @zachlatta @gemmabusoni @MaxWofford

**Comment by hellyeah** [comment]
Talk to mentors/parents/clubmates.

**Comment by jonleung** [comment]
@zachlatta, do we need to revise the timeline somewhere? I ask this because in our old timeline, we said we'd have decisions out to accepted Lab Directors by Tuesday.

**Comment by hellyeah** [comment]
We can do it by Tuesday.

**Comment by jonleung** [comment]
:+1:

**Comment by jonleung** [comment]
Also paraphrasing @hellyeah from https://github.com/hackedu/hackedu/issues/76#issuecomment-133623056:

> We aren't running labs, you are.
> We are not the ones 

Additionally, we may want to include something like:

> We personally are not the ones sitting in the office chair at a co-working space
> in the financial district of San Francisco who are going to figure out how to 
> build a programming club. You, as someone who lives and breathes
> the life of a high schooler knows the trials and tribulations of what it means to be
> a high schooler. People don't believe that you and other high schoolers can do what 
> they can...

**Comment by hellyeah** [comment]
I don't think it's too intense at all -- it's the truth.

**Comment by zachlatta** [comment]
I'm hesitant to include the wording "People don't believe that you and
other high schoolers can do what
they can" because it feels patronizing to me, and exactly what we're
against – telling high schools students what is and isn't.

@jonleung: question about #76. Which comment of @hellyeah's are you
referring to?

On Sun, Aug 23, 2015 at 10:52 PM, David Fontenot <notifications@github.com>
wrote:

> I don't think it's too intense at all -- it's the truth.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/69#issuecomment-134048684>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
@zachlatta how did you do the calls so far? Do we need something formalized here? I trust your judgement and don't think we actually need a script. 

The most important thing is leaving them excited to get Labs started.

**Comment by hellyeah** [comment]
I like this copy from our acceptance email:

"We won't be running hackEDU Labs. You will. As part of the first hackEDU Labs
team, you will lay the foundation for coding communities that will spread
across the globe."

**Comment by hellyeah** [comment]
@zachlatta if this is worth discussing, just ping me on IRC so we can have a brief discussion and I'll write something up.

Otherwise, can you close this issue if you don't need a script for your calls. 

I'm under the impression that you'll be doing all the acceptance calls, but let me know if that changes.

**Comment by zachlatta** [comment]
Yeah, on second thought I don't think we need something formalized here. I'll just be taking lead on the calls and do my best to leave people excited.

Results seem to be good so far!
