### ISSUE TITLE
Schedule interview for South Pasedena High School

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#71]
As discussed in the meeting in #70, we'd like to add South Pasedena High School to the pipeline for our Labs program.

@gemmabusoni can you get in touch with the leader, share what the Labs program is, and then schedule an interview with them that both you and @hellyeah would run?

/cc @jonleung

**Comment by jonleung** [comment]
@gemmabusoni, I know that you talked to them already. Do you have any updates on this?

**Comment by gemmabusoni** [comment]
Got in touch with Mr. Schorr; he's finding leaders. From there, I'll schedule an interview.

**Comment by hellyeah** [comment]
Intro me via Messenger if possible. If you use email (dave@hackedu.us), make sure to ping me to let me know the intro was made.

**Comment by zachlatta** [comment]
@gemmabusoni can you make sure the update the status of this in https://docs.google.com/spreadsheets/d/1Q6E36NK7N_mKp_LJwMW-P3KUZXPsHQTJWyoyKvrneuc/edit#gid=0?

**Comment by jonleung** [comment]
@gemmabusoni, any updates on this?

**Comment by zachlatta** [comment]
@gemmabusoni ping

**Comment by zachlatta** [comment]
@gemmabusoni ping

**Comment by gemmabusoni** [comment]
@zachlatta @hellyeah @jonleung 

He's checking call availability.

**Comment by jonleung** [comment]
:+1:

**Comment by hellyeah** [comment]
Did this happen?

**Comment by gemmabusoni** [comment]
"Shorr passed on info to students (had to go through school to make sure that it was okay that we were contacting them); feel that this will happen sometime this week. Follow-up sent last night."

**Comment by jonleung** [comment]
I think it might be too late for South Pasedena to join the labs program.

Thoughts @zachlatta and @hellyeah?

**Comment by zachlatta** [comment]
Yeah, it's too late to consider them for Labs.

Perhaps we could get them on the waitlist for next semester?

On Mon, Aug 31, 2015 at 1:57 PM, Jonathan Leung <notifications@github.com>
wrote:

> I think it might be too late for South Pasedena to join the labs program.
>
> Thoughts @zachlatta <https://github.com/zachlatta> and @hellyeah
> <https://github.com/hellyeah>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/71#issuecomment-136497161>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Going to go ahead and close this issue because it seems like the original intent, scheduling a Labs interview with them, wasn't satisfied.
