### ISSUE TITLE
Add Raphael and Shriyash's successors to pipeline

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#73]
As discussed in #70.

/cc @hellyeah @gemmabusoni @jonleung

**Comment by jonleung** [comment]
@zachlatta, I think I'm already in touch with Raphael's club leaders. I'll take lead on adding them to the pipeline.

@zachlatta, can you take lead on adding Shriyash's successors to the pipeline?

**Comment by zachlatta** [comment]
Sounds good!

--
Zach Latta
hackEDU| zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta I'm actually in a chat with Shriyash already, I'll just reach out to him about this directly!

**Comment by zachlatta** [comment]
Awesome, thanks!

--
Zach Latta
hackEDU| zach@hackedu.us

**Comment by jonleung** [comment]
Raphael and Shriyash's successors have been added to [the pipeline](https://docs.google.com/spreadsheets/d/1Q6E36NK7N_mKp_LJwMW-P3KUZXPsHQTJWyoyKvrneuc/edit#gid=0).
The statuses of these two clubs are noted in the spreadsheet linked above.
