### ISSUE TITLE
Add meeting notes in regards to schedule to talk about setting broader goal for clubs

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#74]
As discussed in #70, schedule a time to talk about setting a broader goal for our clubs (like an event or competition).

/cc @hellyeah @gemmabusoni @jonleung

**Comment by hellyeah** [comment]
I won't be in-office next Wednesday. How's next Thursday or Friday for this?

**Comment by jonleung** [comment]
@hellyeah, that works for me! Lunch on the roof again perhaps?

**Comment by jonleung** [comment]
Closing this because we thought of something. Our idea is to create a competition between clubs to help people at their school ship the most amount of personal websites. We still need to clarify how we're going to do this though.

**Comment by zachlatta** [comment]
Is this recorded in meeting notes anywhere?

On Fri, Aug 28, 2015 at 11:44 AM, Jonathan Leung <notifications@github.com>
wrote:

> Closed #74 <https://github.com/hackedu/hackedu/issues/74>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/74#event-395363549>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta it hasn't, I'll take lead on that.

**Comment by jonleung** [comment]
I added the meeting notes in pull request #155

**Comment by jonleung** [comment]
Reassigning this to @MaxWofford

**Comment by jonleung** [comment]
Oops, this is not the pull request, assigning myself back.

**Comment by zachlatta** [comment]
Closed by #155.
