### ISSUE TITLE
Write acceptance email for Labs Clubs Organizers

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#76]
This email should outline the objectives of the Labs Program to club leaders accepted into the Labs program. The contract will accompany this email. Languaging may be reused between the email and the contract.

Also, before sending this email to the accepted Lab, we may want to call them first to accept them.
For example the call might go something like the following:

- Hey, you're accepted congrats.
- As a reminder, here is what is expected of you if you accept.
- We will send you this in an email in written form which will have a contract attached to it.

Here are some questions that this email should convey:

- "What is my job as a Lab Director?"
- "Why am I doing this?"
- "What will my work be used for?"
- "Why does any of this matter?"
- "Am I just following instructions the entire time or am I building something for other people to use in the future that will have a massive impact?"
- "Am I special?"

Thoughts on this plan @hellyeah @zachlatta?

**Comment by hellyeah** [comment]
I think the biggest thing to stress is that hackEDU isn't running Labs. 

The Labs Directors (12 high school club leaders we select) run labs together.

Another thing to stress is that an important part of their role will be helping the other labs leaders work through problems their club faces.

**Comment by jonleung** [comment]
@hellyeah, I completely agree!

**Comment by jonleung** [comment]
I also completely updated this task:

- I completely changed the task name
- I completely changed the task description

**Comment by zachlatta** [comment]
@hellyeah, I know we worked on this tonight. Any updates on this?

On Fri, Aug 21, 2015 at 6:19 PM, David Fontenot <notifications@github.com>
wrote:

> I think the biggest thing to stress is that hackEDU isn't running Labs.
>
> The Labs Directors (12 high school club leaders we select) run labs
> together.
>
> Another thing to stress is that an important part of their role will be
> helping the other labs leaders work through problems their club faces.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/76#issuecomment-133623056>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
https://gist.github.com/hellyeah/dac65c733e11237f3f59

**Comment by zachlatta** [comment]
Submitted #98 to address this.
