### ISSUE TITLE
Fill out labs applications spreadsheet with club fair date and first club meeting date from interviews

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#78]
I've been a bit lazy with taking all the information from my interviews (recording in gists) and putting it into the labs spreadsheet: https://docs.google.com/spreadsheets/d/1Q6E36NK7N_mKp_LJwMW-P3KUZXPsHQTJWyoyKvrneuc/edit#gid=0

I want to make sure the spreadsheet is complete before we make decisions on which teams we accept.

**Comment by zachlatta** [comment]
Awesome. I see that you've filled in all of the club fair dates and first meeting dates.

Let's go ahead and close this for now with that. We'll have to assemble a bit more of a formal database when working with the clubs we selected.
