### ISSUE TITLE
Visiting clubs on the East coast.

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#8]
@jonleung what if we did a trip to the East coast and visited as many schools as we can before the school year ends?

We'd want to do this before finals as well, because they'll be super busy then.

**Comment by zachlatta** [comment]
We decided against this offline.

**Comment by MaxWofford** [comment]
@zachlatta Could the reasons for this be brought up in IRC? We might have a hackEDU leader in the area who could help us do this.

**Comment by zachlatta** [comment]
Our reasons for considering a trip to the East coast were twofold:

1) More effectively build club-in-a-box
2) Create fundraising materials (pretty photos, that sort of thing)

We decided that the best way to iterate on the club-in-a-box would be to put together a staggered summer program with multiple concurrent "cohorts". It'd look something like the following, where the numbers are the current club meeting. Notice how they overlap, and how we get 4 chances to iterate on every club meeting.

| Cohort |   |   |   |   |   |   |   |   |   |   |   |
|--------|---|---|---|---|---|---|---|---|---|---|---|
| 1      | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |   |   |   |
| 2      |   | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |   |   |
| 3      |   |   | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |   |
| 4      |   |   |   | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |

In terms of creating fundraising materials, we're not currently blocking on having materials for donors (not to say we don't want them, having photos would be _amazing_). It's just given our current fundraising priorities—$200k by mid-June—my time would be better spent here talking to donors and working with what we have.

I know club leaders are actively working with @jonleung on the club-in-a-box and we could probably get them involved in creating fundraising materials, although I do wonder how eager they'd be to help with that, as it doesn't benefit them much.
