### ISSUE TITLE
Add feedback form in every workshop

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#80]
This issue was transferred from https://github.com/hackedu/hack-camp/issues/493

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by paked** [comment]
@zachlatta this sounds like something packrat could do?

**Comment by MaxWofford** [comment]
@paked That sounds like a great idea!

**Comment by paked** [comment]
@MaxWofford  ![http://media.tumblr.com/tumblr_m93oneRpCZ1r4h8q9.gif](http://media.tumblr.com/tumblr_m93oneRpCZ1r4h8q9.gif)

**Comment by jonleung** [comment]
@MaxWofford just did this!
