### ISSUE TITLE
List all club fair and first meeting dates in applicant spreadsheet

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#82]
If they're not sure when the club fair or their first meeting will be, put "unknown".

Spreadsheet: https://docs.google.com/spreadsheets/d/1Q6E36NK7N_mKp_LJwMW-P3KUZXPsHQTJWyoyKvrneuc

/cc @jonleung @MaxWofford

**Comment by hellyeah** [comment]
Can someone review this and close the issue if they think it's finished.

**Comment by jonleung** [comment]
@hellyeah, for every accepted Lab Director, can we make sure we have the correct dates for the first club meeting and the club fair? Also can you make a distinction between whether they don't know when their first club meeting / club fair is vs we don't know when it is. Right now there are a bunch of cells that say `unknown` in the dates for the club fair and first club meeting.

**Comment by hellyeah** [comment]
Yeah. I'm afraid to reach out to them before Zach calls, but we should probably leave this open until then, or make a new spreadsheet with the accepted directors and the information we want to have on them.

I would be in favor of closing this issue and making a fresh spreadsheet that keeps track of our accepted Labs Directors.

**Comment by jonleung** [comment]
@hellyeah I'm down for something like that. Also see https://github.com/hackedu/hackedu/issues/93

**Comment by zachlatta** [comment]
Is this a duplicate of #78?

**Comment by hellyeah** [comment]
@zachlatta I think so. In the future, how should I handle duplicates. 

I'm worried closing duplicates may add to the number of issues it looked like we've accomplished any given week and would have a negative impact on our ability to assess our momentum as a team.

**Comment by zachlatta** [comment]
If we add the `duplicate` label to any duplicate issues before closing
them, we can always just filter it out in any metrics we have for the team.

On Wed, Aug 26, 2015 at 9:33 AM, David Fontenot <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> I think so. In the future, how
> should I handle duplicates.
>
> I'm worried closing duplicates may add to the number of issues it looked
> like we've accomplished any given week and would have a negative impact on
> our ability to assess our momentum as a team.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/82#issuecomment-135096288>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us
