### ISSUE TITLE
Accept first cohort of clubs

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#83]
We decided to accept a few clubs into the labs program today so we can start building the playbook for the club fair and first meeting now.

/cc @jonleung @MaxWofford

**Comment by zachlatta** [comment]
Alright, I called the first few last night. I'm going to call the remaining clubs today.

(sorry for being late on this!)

**Comment by hellyeah** [comment]
Can we change this issue to more generically be calling accepted club leaders and make calling a few on Monday a sub-task.

**Comment by zachlatta** [comment]
Let's split it up into separate tasks for each cohort. Creating an issue to track accepting cohort 2 now.

**Comment by zachlatta** [comment]
Alright, cohort 2 acceptance is tracked in #94.
