### ISSUE TITLE
Cover club fair in playbook

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#86]
Add sections to the playbook on how to run the club fair. This issue is dependent on #85.

Some notes from our meeting this morning (tracked in hackedu/meta#112):

- Perhaps chat with Aaroh and Abenezer
- Keep Zach in the loop

/cc @MaxWofford @hellyeah

**Comment by jonleung** [comment]
I finished an initial version of this in #120. It is not ready for merge yet because there are still grammar and structural issues.

**Comment by jonleung** [comment]
@hellyeah and I chatted and he's going to take lead on this today (Monday, Aug 30th) with a focus on focusing on making people feel welcome. He's going to make a new branch off of my branch and then submit a pull request to my branch.

**Comment by hellyeah** [comment]
Will spend a lot of time thinking about this and #87 on my flight tomorrow.
