### ISSUE TITLE
Cover first club meeting in playbook

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#87]
Create guidelines and associated content for running the first meeting.

This issue may warrant conversion to a milestone with a bunch of issues for each individual part of the preparation.

Some notes from our planning session this morning (tracked in hackedu/meta#112):

- Everyone needs laptops
- Keep Zach in the loop

/cc @MaxWofford @jonleung

**Comment by jonleung** [comment]
I finished an initial version of this in #121 and #122. It is not ready for merge yet because there are still grammar and structural issues.

**Comment by hellyeah** [comment]
Toastmasters Guide/Checklist: http://www.toastmasters.org/~/media/E51A693193F749AE91FD79F6DB839534.ashx

**Comment by jonleung** [comment]
@hellyeah and I chatted and he's going to take lead on this today (Monday, Aug 30th) with a focus on focusing on making people feel welcome. He's going to make a new branch off of my branch and then submit a pull request to my branch. Assign me to review that pull request.

**Comment by hellyeah** [comment]
Made it more concise. I think we should probably make a separate file for "Greeting people at the door" and "Conversation topics"

**Comment by hellyeah** [comment]
Similarly, "Experiencing success on the first day" probably deserves its own file where we describe why its so important that people ship something on day one.

**Comment by zachlatta** [comment]
#152 will replace this, when completed.

**Comment by jonleung** [comment]
Wait, before we close this issue, don't we need to merge https://github.com/hackedu/hackedu/pull/147

**Comment by hellyeah** [comment]
@jonleung I think #147 is ready to merge. I made the commit that cut 100 lines.

**Comment by zachlatta** [comment]
I believe we're just waiting on a style change in #146 @hellyeah :-).

On Fri, Sep 4, 2015 at 10:36 AM, David Fontenot <notifications@github.com>
wrote:

> @jonleung <https://github.com/jonleung> I think #147
> <https://github.com/hackedu/hackedu/pull/147> is ready to merge. I made
> the commit that cut 100 lines.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/87#issuecomment-137801469>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@hellyeah I left a comment in the pull request

**Comment by hellyeah** [comment]
@zachlatta did you end up taking care of the rebase error? Would love to move this out of the queue.
