### ISSUE TITLE
Too Many Repos?

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#88]
So this isn't quite a blocking factor yet, but just want to prompt people to check if they feel overwhelmed by the number of Github repos. Would an alternate way to manage this, perhaps labels (i.e. a label fundraising, discussion, etc. make more sense?)

Is there a better paradigm?

**Comment by zachlatta** [comment]
Yeah, we should be cautious of creating too many repos. We made this mistake at Yo.

Perhaps we could consolidate this one with the hackedu/hackedu or hackedu/meta repo (could just have a "discussion" tag) once we've renamed hackedu/club-in-a-box to hackedu/hackedu and hackedu/docs to hackedu/meta.

--
Zach Latta
Executive Director of hackEDU (https://hackedu.us)
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by ankitr** [comment]
FYI, all of Google's source is on one repo. (Granted, they have a team designated solely to rewriting SVN (which is what I think they use) to maximize performance.)

**Comment by zachlatta** [comment]
I thought they used Perforce? One giant repo with Perforce is how it's done in the game world as well.

Do you keep in mind they wrote their own issue tracker as well.

**Comment by ankitr** [comment]
Perforce, right. Googlers also built a ton of proxies for using the repo. And yes, along with their own code review tool and all sorts of fun.

**Comment by zachlatta** [comment]
Oh wow, haha. I thought this issue was in https://github.com/hackedu/discussions instead of this repo. Yeah, I think consolidating repos should solve this problem.

Closing for now--reopen or comment if any objections.

**Comment by zachlatta** [comment]
Alright, I went ahead and added a `discussion` tag to https://github.com/hackedu/meta. In the future lets create issues over there and use that tag.
