### ISSUE TITLE
Week 1: Data Collection

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#9]
Get out of the building
  - OBJECTIVES
    - Find out
      - [ ] all the clubs that we have access to
      - [ ] when and for how much longer we can visit each club
      - [ ] biggest reasons for starting and joining clubs
      - [ ] biggest problems for starting, running and being part of a club
      - [ ] biggest wins for starting and joining a club
  
  - METHODOLOGY 
    - [ ] Flush this out more in details
      - [ ] @jonleung
      - [ ] @MaxWofford
      - [ ] @ZachLatta
      
    - CREATE DATA VESSELS:
      - [ ] Finish EXISTING CLUBS Spreadsheet [this spreadsheet](https://docs.google.com/spreadsheets/d/1TkBRXF_jGFTTMxuHs8B47_zPiliaA-Vsvs7vL_LXFyk/edit#gid=0)
        - Sheet 1: High School
        - Sheet 2: Students
      - [ ] Try adding
        - non-hackEDU clubs
        - non-hackEDU members
        - new-hackEDU clubs
        - new-hackEDU members

    - POPULATE :
      - [ ] On FB, find all high school friends & their high schools
        - [ ] @jonleung
        - [ ] @zachlatta
        - [ ] @maxwofford
      - [ ] Hackathon Data
        - [ ] HackGenY
        - [ ] HS Hacks
        - [ ] Gunn Hacks
        - [ ] CodeDay
        - [ ] Figure Out Any Missing Hackathons
      - [ ] Pu

    - COLLECTION:
      - EXISTING STUDENTS FIRST
        - [ ] Create all theq questions you need to ask them
          - [ ] To learn from them
          - [ ] Prepare for visiting them
          - [ ] Getting their phone contact info
          - [ ] Who is going to college? Which colleges?
          - [ ] If applicable, who is taking over leadership of the club
          - [ ] What are you doing over the summer?

        - [ ] For new clubs
          - Do you have a coding club at your school?
            - NO? (Link it to "No Club")
              - Would you be interested in starting a club?
              - What day of the week is your school?
              - I'd love to come visit, who should I talk to for that?
            - YES?
              - Are you a club officer?
                - if YES
                  - Soft
                    - Why did you start a club?
                    - Biggest blocking issues currently, previosly?
                    - Who have you gotten to join your club?
                    - Why do you think they joined?
                  - Hard
                    - What is the name of your school?
                    - Is this the address of the school?
                    - What day of the week do you guys meet? What time?
                    - Which dates will you have club meetings on?
                    - When are some good days to visit
                - if NO
                  - why did you join a club
                  - how did they hear about the club
                  - what do you hope to get out of it

**Comment by MaxWofford** [comment]
@jonleung Is this still relevant?

**Comment by zachlatta** [comment]
Closing for now due to lack of response.
