### ISSUE TITLE
Finalize list of Lab Directors

### ISSUE THREAD

**Issue by hellyeah** [hackedu/hackedu#91]
I've finalized my list of Labs Directors: https://docs.google.com/spreadsheets/d/1Q6E36NK7N_mKp_LJwMW-P3KUZXPsHQTJWyoyKvrneuc/edit#gid=652345821 

If we don't need to go over it again, let's close this.

**Comment by zachlatta** [comment]
I'm cool with this. Thoughts @MaxWofford, @jonleung?

**Comment by MaxWofford** [comment]
:+1:

**Comment by jonleung** [comment]
:+1:
