### ISSUE TITLE
Send books to confirmed Lab Directors

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#92]

**Comment by hellyeah** [comment]
How to Win Friends and Influence People

**Comment by zachlatta** [comment]
I'm down with How to Win Friends and Influence People. Let's plan on sending them that.

**Comment by zachlatta** [comment]
Alright, I've started sending books with a gift note to the leaders. Do note: I need the phone number of each leader to ship it to them (Amazon requires it). I've sent it to the three people we have the phone number down for.

**Comment by zachlatta** [comment]
Just sent it to two more people from the first cohort.

**Comment by hellyeah** [comment]
Who are we missing numbers from?

**Comment by zachlatta** [comment]
From the first cohort:

- Jeremy and Teagan from Lowell

From the second cohort:

- Everyone except for Vene

**Comment by jonleung** [comment]
@zachlatta, are you going to message them for phone numbers?

**Comment by zachlatta** [comment]
Alright, I've shipped books to everyone in the first cohort.

@jonleung, I don't currently have plans on cohort 2 for phone numbers. Could someone else take point on that?

**Comment by zachlatta** [comment]
Also, @jonleung, can you take point on sending them handwritten letters? I'm not sure if I have the bandwidth to do that as well.

**Comment by jonleung** [comment]
@zachlatta, godit!

**Comment by jonleung** [comment]
@zachlatta, were you planning to order the books for cohort 2?

**Comment by jonleung** [comment]
So to be clear, would you like me to order the books for cohort 2 and write the hand written letters for everyone or just the letters?

**Comment by zachlatta** [comment]
I can order the books for cohort 2. I'd appreciate if someone else could write the letters.

Ordering the books takes an absurd amount of time though, probably 1-2 hours.

**Comment by jonleung** [comment]
@zachlatta, sounds good!

**Comment by jonleung** [comment]
I've split this task into two issues:

- send books (covered by this issue)
- send letters (covered by #148)

**Comment by zachlatta** [comment]
I created #149 to track getting the addresses and phone numbers from all of the leaders. This is currently blocking on that.

**Comment by zachlatta** [comment]
Alright, #149 has been closed. We're good to proceed with this.

**Comment by jonleung** [comment]
I finished this and documented my work in clubs.hackedu.us
