### ISSUE TITLE
Find a system to organize the information of all of the clubs

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#93]
**EDITED** _on 08-25-15 7:40pm_:

I feel like we need a place to

- leave notes that we have about calls that we have with organizers
- shows important dates for each club
- who chatted with the club last
- what the things a club currently needs
- what problems a club is currently running into
- what problems a given club is facing

I'm feeling like we need a Salesforce or Basecamp but those sound like the wrong answer.

Also, clubs should be able to see this information about other clubs as well...

Thoughts @MaxWofford @hellyeah @tylermenezes @zachlatta?

**Comment by MaxWofford** [comment]
I think Hack-Camp was a demonstration of how not to do this with GitHub issues. Perhaps Google Apps calendar?

**Comment by tylermenezes** [comment]
What about a folder in Google Drive with a doc for each club? Store important dates in your calendar.

Since this is central to your business operations, if you can't find an off-the-shelf solution that works for you, it might be worth building something custom, as long as you can do it quickly. This is how we came up with Clear, and overall it saves us dramatically more time than it took to develop.

**Comment by jonleung** [comment]
@MaxWofford, Google Apps Calendar seems like a decent strategy. Now we need a place to put the notes.

@tylermenezes, Google Drive could work. @zachlatta, I particularly liked the way that we kept the notes in WorkFlowy but I know you're probably going to push for a private GitHub repo aren't you XD. I'd really like to do something that has live syncing collaboration so the barrier of writing something down is much easier!

**Comment by tylermenezes** [comment]
Oh, you know, I think Confluence might be what you're looking for. In addition to working well as a general wiki, it has templates for taking notes on a meeting (it can also kick-off to-dos in JIRA), and a shared team calendar.

**Comment by MaxWofford** [comment]
@tylermenezes 
> This is how we came up with Clear

Would love to hear about that system^

**Comment by tylermenezes** [comment]
It does everything related to managing CodeDay events, and has a partial API (built-out as needed) that lets other apps (mostly the web frontend, but people have made a few other apps) get access to the data. Mostly, it's useful because it can do things like show a HUD of all event status, give event-by-event financial info, and send automated emails to venues/event staff/etc.

I think Zach probably still has admin access.

**Comment by jonleung** [comment]
Thanks @tylermenezes!

Also, some of my other friends also seem to like Basecamp.

It would be great to have a solution that allows all the other Labs Club to see all the other clubs information. That they can all work together to help each other meet their goals. I really like the idea of having a Google Calendar for this.

**Comment by zachlatta** [comment]
I like the idea of having a shared Google Calendar between all the Lab
Directors that has meeting dates for all of the clubs (perhaps we could
have two calendars, one for each cohort?).

I'm hesitant about using a CRM system that gives the Lab Directors
transparency into our communications with them – there's probably a fair
bit of personal information that will be kept track of.

On Thu, Aug 27, 2015 at 2:39 PM, Jonathan Leung <notifications@github.com>
wrote:

> Thanks @tylermenezes <https://github.com/tylermenezes>!
>
> Also, some of my other friends also seem to like Basecamp.
>
> It would be great to have a solution that allows all the other Labs Club
> to see all the other clubs information. That they can all work together to
> help each other meet their goals. I really like the idea of having a Google
> Calendar for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/93#issuecomment-135563549>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
@jonleung had an idea this morning to create a private GitHub Issue for each school and track any interactions with them in the issue. I think we'll go ahead with that.

Tracking progress on that in #141.
